"""mpm completion subcommand: emit a shell completion script to stdout.

Usage:
  mpm completion bash        -- print the bash completion script
  mpm completion zsh         -- print the zsh completion script
  mpm completion powershell  -- print the PowerShell completion script

The bash and zsh scripts are generated by shtab from the mpm root
ArgumentParser. shtab does not support PowerShell, so the PowerShell script is
emitted by mpm_cli.completions.powershell.generate (FR-31). Windows cmd.exe
has no programmable tab-completion mechanism and is therefore a documented gap
rather than a supported completion shell (FR-39); see docs/shell-completion.md.

Pipe the output to a file and source it in your shell's rc file, or install it
into the shell's completion directory:

  mpm completion bash > /etc/bash_completion.d/mpm
  mpm completion zsh  > "${fpath[1]}/_mpm"
  mpm completion powershell | Out-String | Invoke-Expression

Spec reference: spec/mpm-list-add-lock-features-spec.md
  Section 11.1 -- subcommand contract
  Section 11.2 -- completion coverage matrix (static enum, choices bash/zsh)
  Section 11.9 -- acceptance item 2 (generated scripts pass bash -n / zsh -n)
"""

from __future__ import annotations

import argparse
import sys

import shtab

from mpm_cli.completions import powershell
from mpm_cli.completions.preamble import PREAMBLE


POWERSHELL_SHELL: str = "powershell"


SUPPORTED_SHELLS: list[str] = ["bash", "zsh", POWERSHELL_SHELL]


def register(subparsers: "argparse._SubParsersAction[argparse.ArgumentParser]") -> None:
    """Register the 'completion' subcommand on the top-level argparse subparsers.

    Args:
        subparsers: The subparsers action from the top-level parser.
    """
    parser: argparse.ArgumentParser = subparsers.add_parser(
        "completion",
        add_help=True,
        help="Print a shell completion script to stdout.",
        description=(
            "Emit the shell completion script for mpm to stdout.\n\n"
            "Pipe the output to the appropriate location for your shell:\n\n"
            "  mpm completion bash > /etc/bash_completion.d/mpm\n"
            '  mpm completion zsh  > "${fpath[1]}/_mpm"\n'
            "  mpm completion powershell | Out-String | Invoke-Expression\n\n"
            "Then restart your shell or re-source the completion file.\n\n"
            "cmd.exe has no programmable tab-completion mechanism and is not a\n"
            "supported completion shell; see docs/shell-completion.md.\n\n"
            "See docs/shell-completion.md for full installation instructions."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "shell",
        choices=SUPPORTED_SHELLS,
        metavar="<shell>",
        help=f"Target shell. Choices: {{{', '.join(SUPPORTED_SHELLS)}}}.",
    )
    parser.set_defaults(func=handle)


def handle(args: argparse.Namespace) -> None:
    """Handle the 'completion' subcommand: write the completion script to stdout.

    For bash/zsh, calls shtab.complete() with the root mpm ArgumentParser and
    the PREAMBLE dict from mpm_cli.completions.preamble. For powershell, calls
    mpm_cli.completions.powershell.generate() (shtab does not support
    PowerShell). The generated script is written verbatim to stdout; stderr is
    left untouched on success.

    Args:
        args: Parsed arguments. Must contain:
              - args.shell (str): one of the SUPPORTED_SHELLS values
              - args.parser (argparse.ArgumentParser): the root mpm parser
                injected at invocation time from cli.py
    """

    root_parser: argparse.ArgumentParser = args.parser
    if args.shell == POWERSHELL_SHELL:
        sys.stdout.write(powershell.generate(root_parser))
        return
    sys.stdout.write(shtab.complete(root_parser, args.shell, preamble=PREAMBLE))
