# PowerShell tab-completion for mpm (generated by `mpm completion powershell`).
# Evaluate in your session or PowerShell $PROFILE:
#   mpm completion powershell | Out-String | Invoke-Expression

$_mpm_subcommands = @('add', 'catalog', 'clean', 'completion', 'doctor', 'install', 'marketplace', 'search', 'list', 'outdated', 'remove', 'validate', 'repo', 'why')

Register-ArgumentCompleter -Native -CommandName 'mpm' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $_mpm_subcommands |
        Where-Object { $_ -like "$wordToComplete*" } |
        Sort-Object |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new(
                $_, $_, 'ParameterValue', $_
            )
        }
}
