# AUTOMATICALLY GENERATED by `shtab`

_shtab_mpm_subparsers=('add' 'catalog' 'clean' 'completion' 'doctor' 'install' 'marketplace' 'search' 'list' 'outdated' 'remove' 'validate' 'repo' 'why' '__complete_catalog_entries' '__complete_catalog_versions' '__complete_names_in_lockfile' '__complete_project_versions' '__complete_source_names_in_mpm' '__complete_cached_catalogs' '__resolve_entry_to_repo_url')
_shtab_mpm_catalog_subparsers=('audit')
_shtab_mpm_marketplace_subparsers=('enable' 'disable' 'status')
_shtab_mpm_validate_subparsers=('xml' 'marketplace' 'metadata' 'lockfile')

_shtab_mpm_option_strings=('-h' '--help' '--version' '--quiet' '--verbose' '--no-color' '--no-update-check' '--home' '--store-dir')
_shtab_mpm_add_option_strings=('-h' '--help' '--catalog-source' '--catalog-default-branch' '--as' '--mpm-file' '--force' '--dry-run' '--marketplace-install' '--no-marketplace-install')
_shtab_mpm_catalog_option_strings=('-h' '--help')
_shtab_mpm_catalog_audit_option_strings=('-h' '--help' '--check' '--format' '--strict')
_shtab_mpm_clean_option_strings=('-h' '--help' '--orphans' '--purge' '--purge-all')
_shtab_mpm_completion_option_strings=('-h' '--help')
_shtab_mpm_doctor_option_strings=('-h' '--help' '--mpm-file' '--lock-file' '--strict-drift' '--refresh-completion-cache' '--prune-cache' '--catalog-source')
_shtab_mpm_install_option_strings=('-h' '--help' '--refresh-lock' '--refresh-lock-source' '--reconcile' '--strict-lock' '--strict-drift' '--lock-file')
_shtab_mpm_marketplace_option_strings=('-h' '--help')
_shtab_mpm_marketplace_enable_option_strings=('-h' '--help' '--mpm-file')
_shtab_mpm_marketplace_disable_option_strings=('-h' '--help' '--mpm-file')
_shtab_mpm_marketplace_status_option_strings=('-h' '--help' '--all' '--mpm-file')
_shtab_mpm_search_option_strings=('-h' '--help' '--catalog-source' '--catalog-default-branch' '--format' '--detail' '--tree' '--max-depth' '--no-filter-required' '-A' '--all' '--limit' '--no-limit' '--since-version' '--regex' '--match-fields')
_shtab_mpm_list_option_strings=('-h' '--help' '--declared' '--tree' '--status' '--format' '--mpm-file' '--lock-file')
_shtab_mpm_outdated_option_strings=('-h' '--help' '--catalog-source' '--mpm-file' '--lock-file' '--fail-on-upgrade' '--format')
_shtab_mpm_remove_option_strings=('-h' '--help' '--mpm-file' '--force' '--dry-run')
_shtab_mpm_validate_option_strings=('-h' '--help')
_shtab_mpm_validate_xml_option_strings=('-h' '--help' '--repo-root')
_shtab_mpm_validate_marketplace_option_strings=('-h' '--help' '--repo-root')
_shtab_mpm_validate_metadata_option_strings=('-h' '--help' '--repo-root' '--format')
_shtab_mpm_validate_lockfile_option_strings=('-h' '--help' '--lock-file')
_shtab_mpm_repo_option_strings=('-h' '--help' '--repo-dir')
_shtab_mpm_why_option_strings=('-h' '--help' '--catalog-source' '--mpm-file' '--lock-file' '--format')
_shtab_mpm___complete_catalog_entries_option_strings=('-h' '--help')
_shtab_mpm___complete_catalog_versions_option_strings=('-h' '--help')
_shtab_mpm___complete_names_in_lockfile_option_strings=('-h' '--help')
_shtab_mpm___complete_project_versions_option_strings=('-h' '--help')
_shtab_mpm___complete_source_names_in_mpm_option_strings=('-h' '--help')
_shtab_mpm___complete_cached_catalogs_option_strings=('-h' '--help')
_shtab_mpm___resolve_entry_to_repo_url_option_strings=('-h' '--help')



_shtab_mpm_pos_0_choices=('add' 'catalog' 'clean' 'completion' 'doctor' 'install' 'marketplace' 'search' 'list' 'outdated' 'remove' 'validate' 'repo' 'why' '__complete_catalog_entries' '__complete_catalog_versions' '__complete_names_in_lockfile' '__complete_project_versions' '__complete_source_names_in_mpm' '__complete_cached_catalogs' '__resolve_entry_to_repo_url')
_shtab_mpm_catalog_pos_0_choices=('audit')
_shtab_mpm_catalog_audit___format_choices=('text' 'json')
_shtab_mpm_completion_pos_0_choices=('bash' 'zsh' 'powershell')
_shtab_mpm_marketplace_pos_0_choices=('enable' 'disable' 'status')
_shtab_mpm_search___format_choices=('names' 'json')
_shtab_mpm_list___status_choices=('installed' 'not-installed' 'orphan')
_shtab_mpm_list___format_choices=('table' 'json')
_shtab_mpm_outdated___format_choices=('table' 'json')
_shtab_mpm_validate_pos_0_choices=('xml' 'marketplace' 'metadata' 'lockfile')
_shtab_mpm_validate_metadata___format_choices=('text' 'json')
_shtab_mpm_why___format_choices=('text' 'json')

_shtab_mpm_pos_0_nargs=A...
_shtab_mpm__h_nargs=0
_shtab_mpm___help_nargs=0
_shtab_mpm___version_nargs=0
_shtab_mpm___quiet_nargs=0
_shtab_mpm___verbose_nargs=0
_shtab_mpm___no_color_nargs=0
_shtab_mpm___no_update_check_nargs=0
_shtab_mpm_add_pos_0_nargs=+
_shtab_mpm_add__h_nargs=0
_shtab_mpm_add___help_nargs=0
_shtab_mpm_add___force_nargs=0
_shtab_mpm_add___dry_run_nargs=0
_shtab_mpm_add___marketplace_install_nargs=0
_shtab_mpm_add___no_marketplace_install_nargs=0
_shtab_mpm_catalog_pos_0_nargs=A...
_shtab_mpm_catalog__h_nargs=0
_shtab_mpm_catalog___help_nargs=0
_shtab_mpm_catalog_audit__h_nargs=0
_shtab_mpm_catalog_audit___help_nargs=0
_shtab_mpm_catalog_audit___strict_nargs=0
_shtab_mpm_clean__h_nargs=0
_shtab_mpm_clean___help_nargs=0
_shtab_mpm_clean___orphans_nargs=0
_shtab_mpm_clean___purge_nargs=0
_shtab_mpm_clean___purge_all_nargs=0
_shtab_mpm_completion__h_nargs=0
_shtab_mpm_completion___help_nargs=0
_shtab_mpm_doctor__h_nargs=0
_shtab_mpm_doctor___help_nargs=0
_shtab_mpm_doctor___strict_drift_nargs=0
_shtab_mpm_doctor___refresh_completion_cache_nargs=0
_shtab_mpm_doctor___prune_cache_nargs=0
_shtab_mpm_install__h_nargs=0
_shtab_mpm_install___help_nargs=0
_shtab_mpm_install___refresh_lock_nargs=0
_shtab_mpm_install___reconcile_nargs=0
_shtab_mpm_install___strict_lock_nargs=0
_shtab_mpm_install___strict_drift_nargs=0
_shtab_mpm_marketplace_pos_0_nargs=A...
_shtab_mpm_marketplace__h_nargs=0
_shtab_mpm_marketplace___help_nargs=0
_shtab_mpm_marketplace_enable__h_nargs=0
_shtab_mpm_marketplace_enable___help_nargs=0
_shtab_mpm_marketplace_disable__h_nargs=0
_shtab_mpm_marketplace_disable___help_nargs=0
_shtab_mpm_marketplace_status__h_nargs=0
_shtab_mpm_marketplace_status___help_nargs=0
_shtab_mpm_marketplace_status___all_nargs=0
_shtab_mpm_search__h_nargs=0
_shtab_mpm_search___help_nargs=0
_shtab_mpm_search___detail_nargs=0
_shtab_mpm_search___tree_nargs=0
_shtab_mpm_search___no_filter_required_nargs=0
_shtab_mpm_search__A_nargs=0
_shtab_mpm_search___all_nargs=0
_shtab_mpm_search___no_limit_nargs=0
_shtab_mpm_list__h_nargs=0
_shtab_mpm_list___help_nargs=0
_shtab_mpm_list___declared_nargs=0
_shtab_mpm_list___tree_nargs=0
_shtab_mpm_outdated__h_nargs=0
_shtab_mpm_outdated___help_nargs=0
_shtab_mpm_outdated___fail_on_upgrade_nargs=0
_shtab_mpm_remove_pos_0_nargs=+
_shtab_mpm_remove__h_nargs=0
_shtab_mpm_remove___help_nargs=0
_shtab_mpm_remove___force_nargs=0
_shtab_mpm_remove___dry_run_nargs=0
_shtab_mpm_validate_pos_0_nargs=A...
_shtab_mpm_validate__h_nargs=0
_shtab_mpm_validate___help_nargs=0
_shtab_mpm_validate_xml__h_nargs=0
_shtab_mpm_validate_xml___help_nargs=0
_shtab_mpm_validate_marketplace__h_nargs=0
_shtab_mpm_validate_marketplace___help_nargs=0
_shtab_mpm_validate_metadata__h_nargs=0
_shtab_mpm_validate_metadata___help_nargs=0
_shtab_mpm_validate_lockfile__h_nargs=0
_shtab_mpm_validate_lockfile___help_nargs=0
_shtab_mpm_repo_pos_0_nargs=...
_shtab_mpm_repo__h_nargs=0
_shtab_mpm_repo___help_nargs=0
_shtab_mpm_why__h_nargs=0
_shtab_mpm_why___help_nargs=0
_shtab_mpm___complete_catalog_entries__h_nargs=0
_shtab_mpm___complete_catalog_entries___help_nargs=0
_shtab_mpm___complete_catalog_entries___refresh_only_nargs=0
_shtab_mpm___complete_catalog_versions__h_nargs=0
_shtab_mpm___complete_catalog_versions___help_nargs=0
_shtab_mpm___complete_catalog_versions___refresh_only_nargs=0
_shtab_mpm___complete_names_in_lockfile__h_nargs=0
_shtab_mpm___complete_names_in_lockfile___help_nargs=0
_shtab_mpm___complete_project_versions__h_nargs=0
_shtab_mpm___complete_project_versions___help_nargs=0
_shtab_mpm___complete_source_names_in_mpm__h_nargs=0
_shtab_mpm___complete_source_names_in_mpm___help_nargs=0
_shtab_mpm___complete_cached_catalogs__h_nargs=0
_shtab_mpm___complete_cached_catalogs___help_nargs=0
_shtab_mpm___resolve_entry_to_repo_url__h_nargs=0
_shtab_mpm___resolve_entry_to_repo_url___help_nargs=0


# Custom Preamble

# mpm shell-completion preamble (bash)
# Sourced by the generated completion script produced by `mpm completion bash`.

# _mpm_run_complete <subcommand> [args...]
#
# Common dispatcher called by every named helper.
# Respects MPM_COMPLETION_ENABLED and MPM_COMPLETION_TIMEOUT.
_mpm_run_complete() {
    local _subcommand="$1"
    shift
    # Honour MPM_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${MPM_COMPLETION_ENABLED:-1}" == "0" ]]; then
        COMPREPLY=()
        return 0
    fi
    local _timeout="${MPM_COMPLETION_TIMEOUT:-2}"
    local _output
    if command -v timeout > /dev/null 2>&1; then
        _output=$(timeout "$_timeout" mpm "$_subcommand" "$@" 2>/dev/null) || true
    else
        _output=$(mpm "$_subcommand" "$@" 2>/dev/null) || true
    fi
    mapfile -t COMPREPLY < <(compgen -W "$_output" -- "${cur:-}")
}

_mpm_complete_catalog_entries() {
    local cur="${1:-}"
    _mpm_run_complete __complete_catalog_entries "$cur"
}

_mpm_complete_source_names_in_mpm() {
    local cur="${1:-}"
    _mpm_run_complete __complete_source_names_in_mpm "$cur"
}

_mpm_complete_names_in_lockfile() {
    local cur="${1:-}"
    _mpm_run_complete __complete_names_in_lockfile "$cur"
}

_mpm_complete_catalog_versions() {
    local cur="${1:-}"
    _mpm_run_complete __complete_catalog_versions "$cur"
}

_mpm_complete_project_versions() {
    local repo_url="${1:-}"
    local cur="${2:-}"
    _mpm_run_complete __complete_project_versions "$repo_url" "$cur"
}

_mpm_complete_cached_catalogs() {
    local cur="${1:-}"
    _mpm_run_complete __complete_cached_catalogs "$cur"
}

# _mpm_complete_add_arg -- mid-token splitter helper.
#
# Implements spec Section 11.5: detects the @ separator and routes to the
# appropriate completer. Splits on the LAST @ (spec Section 4.0).
#
# When MPM_COMPLETION_ENABLED=0, returns immediately with empty COMPREPLY
# without shelling out to mpm __resolve_entry_to_repo_url.
_mpm_complete_add_arg() {
    local cur="${1:-}"
    # Honour MPM_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${MPM_COMPLETION_ENABLED:-1}" == "0" ]]; then
        COMPREPLY=()
        return 0
    fi
    if [[ "$cur" == *@* ]]; then
        # Split on the LAST @ per spec Section 4.0.
        local _name="${cur%@*}"
        local _spec="${cur##*@}"
        local _repo_url
        local _timeout="${MPM_COMPLETION_TIMEOUT:-2}"
        if command -v timeout > /dev/null 2>&1; then
            _repo_url=$(timeout "$_timeout" mpm __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        else
            _repo_url=$(mpm __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        fi
        [[ -z "$_repo_url" ]] && return 0
        _mpm_complete_project_versions "$_repo_url" "$_spec"
    else
        _mpm_complete_catalog_entries "$cur"
    fi
}

# End Custom Preamble

# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_mpm() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_mpm
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    COMPREPLY=( $(compgen -f -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_mpm mpm