#compdef mpm

# AUTOMATICALLY GENERATED by `shtab`


_shtab_mpm_commands() {
  local _commands=(
    "__complete_cached_catalogs:Internal hidden subcommand for shell completion of cached catalog identifiers."
    "__complete_catalog_entries:Internal hidden subcommand for shell completion of catalog entry names."
    "__complete_catalog_versions:Internal hidden subcommand for shell completion of catalog version tags and branches."
    "__complete_names_in_lockfile:Internal hidden subcommand for shell completion of lockfile names."
    "__complete_project_versions:Internal hidden subcommand for shell completion of project version tags and branches."
    "__complete_source_names_in_mpm:Internal hidden subcommand for shell completion of .mpm source names."
    "__resolve_entry_to_repo_url:Internal hidden subcommand for the mid-token splitter. Given a catalog entry name, returns the catalog source URL to stdout so the shell helper can route to _mpm_complete_project_versions."
    "add:Resolve catalog entries from a manifest repo and append the"
    "catalog:Subcommands for inspecting and auditing manifest repos."
    "clean:Execute the full MPM clean lifecycle."
    "completion:Emit the shell completion script for mpm to stdout."
    "doctor:Run workspace health checks against the current project directory."
    "install:Execute the full MPM install lifecycle."
    "list:Reconcile the sources declared in .mpm against the sources recorded in"
    "marketplace:Manage the per-dependency Claude marketplace install flag in .mpm."
    "outdated:Compare each MPM_SOURCE_\<name\>_\* block in the .mpm file against"
    "remove:Remove the MPM_SOURCE_\<alias\>_\{URL,REF,PATH,NAME\} block (plus any"
    "repo:Run mpm\'s repo subcommands."
    "search:Print one catalog entry name per line to stdout, sorted"
    "validate:Validate manifest XML files for well-formedness and correctness."
    "why:Reads the .mpm file, resolves the full dependency tree"
  )
  _describe 'mpm commands' _commands
}

_shtab_mpm_catalog_commands() {
  local _commands=(
    "audit:Audit a manifest repo for catalog soft-spot violations."
  )
  _describe 'mpm catalog commands' _commands
}

_shtab_mpm_marketplace_commands() {
  local _commands=(
    "disable:Remove the MPM_SOURCE_\<alias\>_MARKETPLACE line from .mpm for the"
    "enable:Write MPM_SOURCE_\<alias\>_MARKETPLACE\=true into .mpm for the"
    "status:Print a table of every dependency in .mpm, its catalog \<type\>, and"
  )
  _describe 'mpm marketplace commands' _commands
}

_shtab_mpm_validate_commands() {
  local _commands=(
    "lockfile:Check that the consumer-project .mpm declarations agree with the"
    "marketplace:Validate all marketplace XML manifests under repo-specs\/."
    "metadata:Check every \*-marketplace.xml under repo-specs\/ for in-repo soft-spot violations (spec Section 3.5 rules 1, 2, 3)."
    "xml:Validate all XML manifest files under repo-specs\/."
  )
  _describe 'mpm validate commands' _commands
}

_shtab_mpm_options=(
  {-h,--help}"[Show this and exit.]:help:"
  "(- : *)--version[show program\'s version number and exit]"
  "--quiet[Suppress all output except errors. Mutually exclusive with --verbose.]"
  "--verbose[Enable debug-level output. Mutually exclusive with --quiet.]"
  "--no-color[Disable ANSI color output. Takes precedence over the NO_COLOR environment variable and TTY auto-detection.]"
  "--no-update-check[Skip the best-effort \'update available\' PyPI lookup for this invocation. Equivalent to setting MPM_SKIP_UPDATE_CHECK\=1.]"
  {--home,--store-dir}"[Use \<path\> as the shared mpm home root (the content-addressed store and caches live under it). Takes precedence over the MPM_HOME environment variable and the \~\/.mpm-home default. --store-dir is an accepted alias.]:home:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_defaults_added=0

_shtab_mpm___complete_cached_catalogs_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_cached_catalogs_defaults_added=0

_shtab_mpm___complete_catalog_entries_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_catalog_entries_defaults_added=0

_shtab_mpm___complete_catalog_versions_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_catalog_versions_defaults_added=0

_shtab_mpm___complete_names_in_lockfile_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_names_in_lockfile_defaults_added=0

_shtab_mpm___complete_project_versions_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Project repository URL to query for version tags and branches.:"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_project_versions_defaults_added=0

_shtab_mpm___complete_source_names_in_mpm_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___complete_source_names_in_mpm_defaults_added=0

_shtab_mpm___resolve_entry_to_repo_url_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Catalog entry name to resolve to a repo URL.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm___resolve_entry_to_repo_url_defaults_added=0

_shtab_mpm_add_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the MPM_CATALOG_SOURCES env var. Required when MPM_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--catalog-default-branch[Branch to use for a catalog source supplied without an \'\@ref\'. Precedence\: an inline \'\@ref\' on the source \> this flag \> the MPM_CATALOG_DEFAULT_BRANCH env var (default \'main\') \> the literal \'auto\', which resolves the remote HEAD symref via \'git ls-remote --symref\'. A defaulted branch is verified to exist on the remote (fail fast) and a single WARNING naming it is written to stderr.]:catalog_default_branch:"
  "--as[Override the auto-computed local alias for the (single) added
entry. The alias charset is \[A-Za-z0-9_\] with no \'__\' run. When
the alias is already mapped to a different source it is a hard
error (use --force to overwrite, or \'mpm remove \<alias\>\'
first). Without --as, the alias is the sanitized manifest name,
auto-suffixed deterministically on a cross-source collision.]:alias_override:"
  "--mpm-file[Destination .mpm file path. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--force[Overwrite an existing alias block when re-adding the same
package (same source\@ref), and re-pin its .mpm.lock entry
while keeping the dep\'s NAME. Without this flag, a re-add of an
existing alias is a hard error (with a diff and the guiding
message). A cross-source collision (a different source for the
same manifest name) is auto-suffixed deterministically and is
never an error, with or without --force.]"
  "--dry-run[Print the diff that WOULD be written to the destination
.mpm file (\'\+\' for added lines, \'-\' for removed lines when a
--force overwrite replaces an existing block). Makes no on-disk
change. Exits 0. Alias resolution still runs first, so a
within-request duplicate or a re-add of an existing alias
(without --force) is reported before any diff is shown.]"
  "--marketplace-install[Force the added dependency to register as a Claude marketplace
(write MPM_SOURCE_\<alias\>_MARKETPLACE\=true), overriding the
auto-detected \<catalog-metadata\>\<type\>. Errors if the entry is not
a \'claude-marketplace\' type. Mutually exclusive with
--no-marketplace-install.]"
  "--no-marketplace-install[Force the added dependency to NOT register as a marketplace (omit
the MPM_SOURCE_\<alias\>_MARKETPLACE line), overriding the
auto-detected \<catalog-metadata\>\<type\>. Mutually exclusive with
--marketplace-install.]"
  "(*):One or more catalog entry names, optionally suffixed with \'\@\<spec\>\':"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_add_defaults_added=0

_shtab_mpm_catalog_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_catalog_defaults_added=0

_shtab_mpm_catalog_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--check[Comma-separated list of checks to run, or \'all\' (default). Valid values\: all, entry-name-uniqueness, metadata, remote-url, source-name-derivation, tag-format. Cannot mix \'all\' with individual check names.]:check:"
  "--format[Output format. \'text\' prints one finding per line with ERROR\:\/WARN\:\/INFO\: prefix. \'json\' prints a single JSON object \{\"findings\"\: \[...\]\}. Default\: text. Env\: MPM_CATALOG_AUDIT_FORMAT.]:format:(text json)"
  "--strict[Promotes warnings to errors when enabled\; exits non-zero when any WARN-level finding is present. Prints a one-line summary to stderr naming the warning count when warnings exist.]"
  ":Path to a local manifest repo directory (must contain repo-specs\/) or a remote \'\<git_url\>\@\<ref\>\' catalog source. Defaults to \'.\' (cwd).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_catalog_audit_defaults_added=0

_shtab_mpm_clean_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--orphans[Also unregister mpm-owned marketplaces no longer referenced by .mpm\/.mpm.lock (prunes them from \~\/.claude).]"
  "--purge[Also delete this project\'s .mpm and .mpm.lock files after the normal teardown (full removal of the project\'s mpm config).]"
  "--purge-all[Everything --purge does, and also remove the shared mpm home store directory (MPM_HOME, default \~\/.mpm-home) used by all projects. Runs even when no .mpm project is present (removes only the shared store).]"
  ":Path to the .mpm configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_clean_defaults_added=0

_shtab_mpm_completion_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Target shell. Choices\: \{bash, zsh, powershell\}.:(bash zsh powershell)"
  ":Target shell. Choices\: \{bash, zsh, powershell\}.:(bash zsh powershell)"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_completion_defaults_added=0

_shtab_mpm_doctor_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--mpm-file[Path to the .mpm file that identifies the workspace root. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--lock-file[Path to the .mpm.lock lockfile. Defaults to \'\<mpm-file\>.lock\' (e.g. .\/.mpm.lock). Overridden by the MPM_LOCK_FILE environment variable.]:lock_file:"
  "--strict-drift[Promote branch-drift findings from info-level to error-level. With this flag, mpm doctor returns exit code 1 when any branch-pinned source\'s tip SHA differs from the locked SHA.]"
  "--refresh-completion-cache[Subcheck 8\: invalidate the shell completion cache under \<MPM_HOME\>\/cache\/completion-cache\/. Removes all files there and recreates the directory with mode 0700. Reports an info finding with the count of files removed.]"
  "--prune-cache[Subcheck 10\: remove cache files under the MPM_HOME cache whose last-access time is older than MPM_CACHE_PRUNE_AGE_DAYS days (default 30). Reports an info finding with the count and total byte size pruned. Also reports stale .mpm-data\/.mpm-install.lock files as advisory (does not delete them).]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the MPM_CATALOG_SOURCES env var. Required when MPM_CATALOG_SOURCES configures no single source.]:catalog_source:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_doctor_defaults_added=0

_shtab_mpm_install_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--refresh-lock[Ignore the existing lockfile, re-resolve every transitive version from scratch against the committed .mpm source declarations, and overwrite .mpm.lock with the new state.]"
  "--refresh-lock-source[Re-resolve exactly one top-level source\'s full chain from the committed .mpm while preserving every other source\'s lockfile entries verbatim. NAME may be a source name (the MPM_SOURCE_\<name\> key) or a catalog entry name resolved via derive_source_name.]:refresh_lock_source:"
  "--reconcile[Opt in to the lenient npm-install reconcile when .mpm and .mpm.lock have drifted. By default a drifted pair fails fast (exit 1) without mutating the lock. With this flag, mpm prunes orphaned lock entries, re-resolves added or changed sources, replays unchanged sources, and rewrites .mpm.lock on success. Use --refresh-lock to rebuild the entire lock from scratch instead.]"
  "--strict-lock[Upgrade orphaned lock entries to a hard error in the consistent state. An orphaned lock entry is a source present in .mpm.lock but absent from .mpm (e.g. after \'mpm remove\'). Drift between .mpm and .mpm.lock already fails fast by default\; this flag additionally fails on an orphan that survives a mpm_hash match. Remediation\: restore the missing MPM_SOURCE_\<name\>_\* triples in .mpm, or run with --reconcile to prune.]"
  "--strict-drift[Upgrade branch drift to a hard error in the consistent state. Branch drift occurs when the lockfile records a SHA for a branch-shaped source but the branch\'s current tip on the remote is a different SHA. Without this flag, the locked SHA is reused and an info-line is emitted (the content pin is replayed). With this flag, mpm exits with an error listing every drifted source. Remediation\: run \'mpm install --refresh-lock-source \<source\>\' to accept the new branch tip.]"
  "--lock-file[Path to the lock file. Defaults to \<mpm-file\>.lock (derived from --mpm-file). The MPM_LOCK_FILE environment variable is consulted when this flag is absent\; the CLI flag takes precedence when both are set.]:lock_file:"
  ":Path to the .mpm configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_install_defaults_added=0

_shtab_mpm_list_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--declared[Show only sources declared in .mpm (installed and not-installed)\; omit orphan sources that are in .mpm.lock but no longer declared.]"
  "--tree[Expand each installed source to its transitive packages (from .mpm.lock).]"
  "--status[Filter to sources with the given status\: installed, not-installed, orphan.]:status:(installed not-installed orphan)"
  "--format[Output format\: \'table\' (default) or \'json\'. Overridden by the MPM_LIST_OUTPUT_FORMAT environment variable\; the CLI flag takes precedence when both are set.]:format:(table json)"
  "--mpm-file[Path to the .mpm file. Defaults to auto-discovery (walk up from the current directory). Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--lock-file[Path to the .mpm.lock file. Defaults to \<mpm-file\>.lock. Overridden by the MPM_LOCK_FILE environment variable\; the CLI flag takes precedence when both are set.]:lock_file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_list_defaults_added=0

_shtab_mpm_marketplace_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_marketplace_defaults_added=0

_shtab_mpm_marketplace_disable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--mpm-file[Path to the .mpm file to read\/modify. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  ":The source alias to disable (canonical alias or original entry name).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_marketplace_disable_defaults_added=0

_shtab_mpm_marketplace_enable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--mpm-file[Path to the .mpm file to read\/modify. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  ":The source alias to enable (canonical alias or original entry name).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_marketplace_enable_defaults_added=0

_shtab_mpm_marketplace_status_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--all[Show every dependency, including those that are not a marketplace
type. Without --all, only marketplace-typed dependencies are listed.]"
  "--mpm-file[Path to the .mpm file to read\/modify. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_marketplace_status_defaults_added=0

_shtab_mpm_outdated_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the MPM_CATALOG_SOURCES env var. Required when MPM_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--mpm-file[Path to the .mpm file. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--lock-file[Path to the .mpm.lock file. When present, provides the current resolved SHA. When absent, the command live-resolves against the catalog. Defaults to \<mpm-file\>.lock. Overridden by the MPM_LOCK_FILE environment variable\; the CLI flag takes precedence when both are set.]:lock_file:"
  "--fail-on-upgrade[Exit 1 when ANY source has an available upgrade (upgrade-type \!\= \'none\'). Default is to always exit 0 (parity with pip list --outdated, npm outdated, cargo outdated). Use this flag in CI pipelines to gate on lockfile freshness\: the build fails when any source is upgradable, prompting the operator to refresh the lockfile. Spec reference\: spec\/mpm-list-add-lock-features-spec.md Section 0.2 and Section 4.4 \'Exit code\'.]"
  "--format[Output format\: \'table\' (default) or \'json\'. The \'json\' format emits a top-level array of objects, one per source, with keys\: name, current, latest-matching-spec, latest-available, upgrade-type. Overridden by the MPM_OUTDATED_FORMAT environment variable\; the CLI flag takes precedence when both are set.]:format:(table json)"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_outdated_defaults_added=0

_shtab_mpm_remove_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--mpm-file[Path to the .mpm file to modify. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--force[Silently skip sources that are not fully present in the .mpm file (used to clean up partially-orphaned entries). Known sources are still removed atomically.]"
  "--dry-run[Preview mode\: shows which lines would be removed. Each removed line is
printed to stdout with a \'-\' prefix. Makes no on-disk change. Exits 0.
The file-writing rules (line-ending preservation, blank-run collapse,
trailing-newline normalisation) apply only to the normal write path,
not to the dry-run output.]"
  "(*):One or more source aliases to remove. Each may be the canonical alias:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_remove_defaults_added=0

_shtab_mpm_repo_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-dir[Path to the .repo directory for the repo tool (default\: \$\{MPM_REPO_DIR\} or \'.repo\')]:repo_dir:"
  "(-)*:Arguments forwarded verbatim to the repo tool:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_repo_defaults_added=0

_shtab_mpm_search_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "*--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the MPM_CATALOG_SOURCES env var. Required when MPM_CATALOG_SOURCES configures no single source. May be repeated to search several sources\; the supplied flags fully replace MPM_CATALOG_SOURCES for this invocation.]:catalog_source:"
  "--catalog-default-branch[Branch to use for a catalog source supplied without an \'\@ref\'. Precedence\: an inline \'\@ref\' on the source \> this flag \> the MPM_CATALOG_DEFAULT_BRANCH env var (default \'main\') \> the literal \'auto\', which resolves the remote HEAD symref via \'git ls-remote --symref\'. A defaulted branch is verified to exist on the remote (fail fast) and a single WARNING naming it is written to stderr.]:catalog_default_branch:"
  "--format[Output format. \'names\' (default)\: one entry name per line, pipeable into mpm add. \'json\'\: structured JSON array. Default mode and --detail mode emit \{name, display-name, type, description, version\} objects\; -A\/--all mode emits \{name, version, ref, sha\} objects. The MPM_LIST_FORMAT environment variable sets the format when this flag is absent\; the CLI flag takes precedence when both are set. --format json is incompatible with --tree (hard error at validation time).]:list_format:(names json)"
  "--detail[Print a human-readable multi-line record per entry (display-name, description, version, type). Human-readable only -- not pipeable into mpm add. For machine consumers, combine with --format json.]"
  "--tree[Render a three-layer ASCII dependency tree per entry\: the catalog entry (root), the XML manifests reachable via transitive \<include\> directives, and the \<project\> repos referenced by those manifests. Each node shows the version resolved at command-execution time. Mutually exclusive with -A\/--all. Subject to the threshold guardrail (MPM_TREE_NO_FILTER_THRESHOLD, default 20)\: when the catalog exceeds the threshold, supply a filter -- positional substring, --regex, --max-depth 0 -- or pass --no-filter-required.]"
  "--max-depth[Cap the tree depth rendered by --tree. 0 \= root entry node only (no XML or project layers). 1 \= root \+ XML layer only. Default\: unlimited. --max-depth 0 also satisfies the threshold guardrail as a valid filter.]:max_depth:"
  "--no-filter-required[Bypass the threshold guardrail for --tree. Normally, catalogs with more than MPM_TREE_NO_FILTER_THRESHOLD (default 20) entries require a filter (positional substring, --regex, or --max-depth 0) to avoid accidental full-catalog tree renders. Pass this flag to bypass the check.]"
  {-A,--all}"[Show all tagged versions of each matching manifest instead of the latest-only default. Walks all historical tagged versions of the manifest repo and emits one \<name\>\@\<version\> row per catalog entry per version. Versions are ordered newest-first by PEP 440 natural sort\; entries within each version are sorted lexicographically. Mutually exclusive with --tree. Default cap\: MPM_LIST_LIMIT (default 50, overridable via env var). Use --limit N or --no-limit to control the number of versions walked.]"
  "--limit[Cap the number of versions walked by -A\/--all. Default\: MPM_LIST_LIMIT (default 50, overridable via the MPM_LIST_LIMIT environment variable). Mutually exclusive with --no-limit.]:limit:"
  "--no-limit[Walk all PEP 440-valid tags when using -A\/--all, with no cap. Equivalent to --limit \<very-large-number\>. Mutually exclusive with --limit.]"
  "--since-version[Filter the versions walked by -A\/--all to those matching a PEP 440 specifier constraint (e.g. \'\>\=1.0,\<2.0\'). The constraint is evaluated against the PEP 440 version parsed from each tag name. Tags that do not parse as PEP 440 are skipped. Example\: --since-version \'\>\=1.0,\<2.0\']:since_version:"
  "--regex[Regular-expression filter (Python re.search). When supplied, only entries whose name, display-name, description, or keywords match the pattern are returned. The keywords field matches when any element satisfies re.search. Mutually exclusive with the positional \<substring\>. Use --match-fields to restrict the fields checked. Example\: --regex \'\^foo\']:regex:"
  "--match-fields[Comma-separated list of fields to check when filtering. Legal values\: name, display-name, description, keywords. Default (when --match-fields is not supplied)\: all four fields. Requires the positional \<substring\> or --regex to be present\; supplying --match-fields without a filter is a hard error. Example\: --match-fields keywords]:match_fields:"
  ":Optional case-sensitive substring filter. When supplied, only entries whose name, display-name, description, or keywords contain the substring are returned. Mutually exclusive with --regex. Use --match-fields to restrict the fields checked.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_search_defaults_added=0

_shtab_mpm_validate_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_validate_defaults_added=0

_shtab_mpm_validate_lockfile_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--lock-file[Path to the lock file. Defaults to \<mpm-file\>.lock (derived from the .mpm path). The MPM_LOCK_FILE environment variable is consulted when this flag is absent\; the CLI flag takes precedence when both are set.]:lock_file:"
  ":Path to the .mpm configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_validate_lockfile_defaults_added=0

_shtab_mpm_validate_marketplace_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_validate_marketplace_defaults_added=0

_shtab_mpm_validate_metadata_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
  "--format[Output format. \'text\' prints one finding per line with ERROR\:\/WARN\:\/INFO\: prefix. \'json\' prints a single JSON object \{\"findings\"\: \[...\]\}. Default\: text.]:format:(text json)"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_validate_metadata_defaults_added=0

_shtab_mpm_validate_xml_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_validate_xml_defaults_added=0

_shtab_mpm_why_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the MPM_CATALOG_SOURCES env var. Required when MPM_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--mpm-file[Path to the .mpm file. Defaults to \'.\/.mpm\'. Overridden by the MPM_MPM_FILE environment variable\; the CLI flag takes precedence when both are set.]:mpm_file:"
  "--lock-file[Path to the .mpm.lock file. When present, the tree is built from lockfile entries (no git calls). When absent, the command live-resolves against the catalog. Defaults to \<mpm-file\>.lock. Overridden by the MPM_LOCK_FILE environment variable\; the CLI flag takes precedence when both are set.]:lock_file:"
  "--format[Output format\: \'text\' (default) or \'json\'. Overridden by the MPM_WHY_FORMAT environment variable\; the CLI flag takes precedence when both are set.]:format:(text json)"
  ":The project URL, XML manifest path, source name, or transitive include name to look up. Project URLs are canonicalized via canonicalize_repo_url before matching. XML manifest paths are matched by exact string equality. Source and include names are normalized via derive_source_name (case- and separator-insensitive).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_mpm_why_defaults_added=0


_shtab_mpm() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->mpm'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_mpm_defaults_added )); then
    if (( ${_shtab_mpm_options[(I)${(q)one_or_more}*]} +          ${_shtab_mpm_options[(I)${(q)remainder}*]} +          ${_shtab_mpm_options[(I)${(q)default}]} == 0 )); then
      _shtab_mpm_options+=(': :_shtab_mpm_commands' '*::: :->mpm')
    fi
    _shtab_mpm_defaults_added=1
  fi
  _arguments -C -s $_shtab_mpm_options

  case $state in
    mpm)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_mpm-$line[1]:"
      case $line[1] in
        __complete_cached_catalogs) _arguments -C -s $_shtab_mpm___complete_cached_catalogs_options ;;
        __complete_catalog_entries) _arguments -C -s $_shtab_mpm___complete_catalog_entries_options ;;
        __complete_catalog_versions) _arguments -C -s $_shtab_mpm___complete_catalog_versions_options ;;
        __complete_names_in_lockfile) _arguments -C -s $_shtab_mpm___complete_names_in_lockfile_options ;;
        __complete_project_versions) _arguments -C -s $_shtab_mpm___complete_project_versions_options ;;
        __complete_source_names_in_mpm) _arguments -C -s $_shtab_mpm___complete_source_names_in_mpm_options ;;
        __resolve_entry_to_repo_url) _arguments -C -s $_shtab_mpm___resolve_entry_to_repo_url_options ;;
        add) _arguments -C -s $_shtab_mpm_add_options ;;
        catalog) _shtab_mpm_catalog ;;
        clean) _arguments -C -s $_shtab_mpm_clean_options ;;
        completion) _arguments -C -s $_shtab_mpm_completion_options ;;
        doctor) _arguments -C -s $_shtab_mpm_doctor_options ;;
        install) _arguments -C -s $_shtab_mpm_install_options ;;
        list) _arguments -C -s $_shtab_mpm_list_options ;;
        marketplace) _shtab_mpm_marketplace ;;
        outdated) _arguments -C -s $_shtab_mpm_outdated_options ;;
        remove) _arguments -C -s $_shtab_mpm_remove_options ;;
        repo) _arguments -C -s $_shtab_mpm_repo_options ;;
        search) _arguments -C -s $_shtab_mpm_search_options ;;
        validate) _shtab_mpm_validate ;;
        why) _arguments -C -s $_shtab_mpm_why_options ;;
      esac
  esac
}

_shtab_mpm_catalog() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->catalog'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_mpm_catalog_defaults_added )); then
    if (( ${_shtab_mpm_catalog_options[(I)${(q)one_or_more}*]} +          ${_shtab_mpm_catalog_options[(I)${(q)remainder}*]} +          ${_shtab_mpm_catalog_options[(I)${(q)default}]} == 0 )); then
      _shtab_mpm_catalog_options+=(': :_shtab_mpm_catalog_commands' '*::: :->catalog')
    fi
    _shtab_mpm_catalog_defaults_added=1
  fi
  _arguments -C -s $_shtab_mpm_catalog_options

  case $state in
    catalog)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_mpm_catalog-$line[1]:"
      case $line[1] in
        audit) _arguments -C -s $_shtab_mpm_catalog_audit_options ;;
      esac
  esac
}

_shtab_mpm_marketplace() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->marketplace'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_mpm_marketplace_defaults_added )); then
    if (( ${_shtab_mpm_marketplace_options[(I)${(q)one_or_more}*]} +          ${_shtab_mpm_marketplace_options[(I)${(q)remainder}*]} +          ${_shtab_mpm_marketplace_options[(I)${(q)default}]} == 0 )); then
      _shtab_mpm_marketplace_options+=(': :_shtab_mpm_marketplace_commands' '*::: :->marketplace')
    fi
    _shtab_mpm_marketplace_defaults_added=1
  fi
  _arguments -C -s $_shtab_mpm_marketplace_options

  case $state in
    marketplace)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_mpm_marketplace-$line[1]:"
      case $line[1] in
        disable) _arguments -C -s $_shtab_mpm_marketplace_disable_options ;;
        enable) _arguments -C -s $_shtab_mpm_marketplace_enable_options ;;
        status) _arguments -C -s $_shtab_mpm_marketplace_status_options ;;
      esac
  esac
}

_shtab_mpm_validate() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->validate'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_mpm_validate_defaults_added )); then
    if (( ${_shtab_mpm_validate_options[(I)${(q)one_or_more}*]} +          ${_shtab_mpm_validate_options[(I)${(q)remainder}*]} +          ${_shtab_mpm_validate_options[(I)${(q)default}]} == 0 )); then
      _shtab_mpm_validate_options+=(': :_shtab_mpm_validate_commands' '*::: :->validate')
    fi
    _shtab_mpm_validate_defaults_added=1
  fi
  _arguments -C -s $_shtab_mpm_validate_options

  case $state in
    validate)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_mpm_validate-$line[1]:"
      case $line[1] in
        lockfile) _arguments -C -s $_shtab_mpm_validate_lockfile_options ;;
        marketplace) _arguments -C -s $_shtab_mpm_validate_marketplace_options ;;
        metadata) _arguments -C -s $_shtab_mpm_validate_metadata_options ;;
        xml) _arguments -C -s $_shtab_mpm_validate_xml_options ;;
      esac
  esac
}

# Custom Preamble

# mpm shell-completion preamble (zsh)
# Sourced by the generated completion script produced by `mpm completion zsh`.

# _mpm_run_complete <subcommand> [args...]
#
# Common dispatcher called by every named helper.
# Respects MPM_COMPLETION_ENABLED and MPM_COMPLETION_TIMEOUT.
_mpm_run_complete() {
    local _subcommand="$1"
    shift
    # Honour MPM_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${MPM_COMPLETION_ENABLED:-1}" == "0" ]]; then
        return 0
    fi
    local _timeout="${MPM_COMPLETION_TIMEOUT:-2}"
    local -a _lines
    if command -v timeout > /dev/null 2>&1; then
        _lines=("${(@f)$(timeout "$_timeout" mpm "$_subcommand" "$@" 2>/dev/null)}")
    else
        _lines=("${(@f)$(mpm "$_subcommand" "$@" 2>/dev/null)}")
    fi
    # Filter empty lines that result from trailing newlines in subprocess output.
    local -a _candidates
    local _item
    for _item in "${_lines[@]}"; do
        [[ -n "$_item" ]] && _candidates+=("$_item")
    done
    [[ ${#_candidates[@]} -gt 0 ]] && compadd -- "${_candidates[@]}"
}

_mpm_complete_catalog_entries() {
    local cur="${1:-}"
    _mpm_run_complete __complete_catalog_entries "$cur"
}

_mpm_complete_source_names_in_mpm() {
    local cur="${1:-}"
    _mpm_run_complete __complete_source_names_in_mpm "$cur"
}

_mpm_complete_names_in_lockfile() {
    local cur="${1:-}"
    _mpm_run_complete __complete_names_in_lockfile "$cur"
}

_mpm_complete_catalog_versions() {
    local cur="${1:-}"
    _mpm_run_complete __complete_catalog_versions "$cur"
}

_mpm_complete_project_versions() {
    local repo_url="${1:-}"
    local cur="${2:-}"
    _mpm_run_complete __complete_project_versions "$repo_url" "$cur"
}

_mpm_complete_cached_catalogs() {
    local cur="${1:-}"
    _mpm_run_complete __complete_cached_catalogs "$cur"
}

# _mpm_complete_add_arg -- mid-token splitter helper.
#
# Implements spec Section 11.5: detects the @ separator and routes to the
# appropriate completer. Splits on the LAST @ (spec Section 4.0).
#
# When MPM_COMPLETION_ENABLED=0, returns immediately without shelling out
# to mpm __resolve_entry_to_repo_url.
_mpm_complete_add_arg() {
    local cur="${1:-}"
    # Honour MPM_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${MPM_COMPLETION_ENABLED:-1}" == "0" ]]; then
        return 0
    fi
    if [[ "$cur" == *@* ]]; then
        # Split on the LAST @ per spec Section 4.0.
        local _name="${cur%@*}"
        local _spec="${cur##*@}"
        local _repo_url
        local _timeout="${MPM_COMPLETION_TIMEOUT:-2}"
        if command -v timeout > /dev/null 2>&1; then
            _repo_url=$(timeout "$_timeout" mpm __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        else
            _repo_url=$(mpm __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        fi
        [[ -z "$_repo_url" ]] && return 0
        _mpm_complete_project_versions "$_repo_url" "$_spec"
    else
        _mpm_complete_catalog_entries "$cur"
    fi
}

# End Custom Preamble


typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_mpm -N mpm
else
  # autoload from fpath, call function directly
  _shtab_mpm "$@"
fi
