"""Integration tests for bash shell completion via compgen -F / _shtab_mpm.

Implements Section 11.9 acceptance item 1: every row in the Section 11.2
completion-coverage matrix has a passing integration test asserting the
expected candidate list.

Each parametrized case corresponds to one row of Section 11.2.  The test
runner sources the live ``mpm completion bash`` output into a real bash
process (>= 4.0).

For STATIC rows (choices-based flags and subcommand enums), the test calls
``_shtab_mpm`` with the appropriate ``COMP_LINE`` / ``COMP_WORDS`` /
``COMP_CWORD`` environment and captures ``COMPREPLY``.

For DYNAMIC rows, the test calls the preamble helper functions directly
(e.g., ``_mpm_complete_catalog_entries``, ``_mpm_complete_add_arg``).
The preamble helpers are defined in the completion script generated by
``mpm completion bash`` and are available after sourcing that script.
The test places a stub ``mpm`` executable on ``$PATH`` and asserts:
  (a) the stub was invoked exactly once with the expected subcommand and
      ``<current-token>`` argument, and
  (b) ``COMPREPLY`` matches the stub's output.

AC-FUNC-006 -- bash version check -- is an assertion (not a skip) so the
suite fails loudly on a bash < 4.0 interpreter.

AC-FUNC-007 -- the generated completion script is validated with ``bash -n``
before every parametrized case.
"""

from __future__ import annotations

import os
import re
import stat
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path
from typing import Optional

import pytest


def _mpm_completion_script() -> str:
    """Return the live ``mpm completion bash`` output."""
    result = subprocess.run(
        [sys.executable, "-m", "mpm_cli", "completion", "bash"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"mpm completion bash failed with exit {result.returncode}. stderr: {result.stderr!r}"
    )
    assert result.stdout.strip(), "mpm completion bash produced empty output"
    return result.stdout


def _bash_syntax_check(script_content: str) -> None:
    """Assert that ``script_content`` is valid bash syntax via ``bash -n``."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".bash", delete=False) as tmp:
        tmp.write(script_content)
        tmp_path = tmp.name
    try:
        check = subprocess.run(["bash", "-n", tmp_path], capture_output=True, text=True)
        assert check.returncode == 0, f"bash -n syntax check failed.\nstderr: {check.stderr!r}"
    finally:
        os.unlink(tmp_path)


def _assert_bash_version_gte_4() -> None:
    """Assert the bash interpreter is >= 4.0; fail with an actionable message if not.

    AC-FUNC-006: This is NOT a skip -- a bash < 4.0 environment means the
    completion system will not function and is a test infrastructure failure.
    """
    result = subprocess.run(["bash", "--version"], capture_output=True, text=True)
    assert result.returncode == 0, (
        "Could not determine bash version: 'bash --version' failed. Ensure bash is installed and on PATH."
    )

    first_line = result.stdout.splitlines()[0] if result.stdout else ""
    match = re.search(r"version\s+(\d+)\.(\d+)", first_line)
    assert match is not None, (
        f"Could not parse bash version from output: {first_line!r}. Ensure bash >= 4.0 is installed."
    )
    major = int(match.group(1))
    minor = int(match.group(2))
    assert (major, minor) >= (4, 0), (
        f"bash version {major}.{minor} is too old. "
        "mpm shell completion requires bash >= 4.0. "
        "macOS stock bash 3.2 is NOT supported; install bash via Homebrew "
        "('brew install bash') and ensure it is first on PATH."
    )


def _write_stub_mpm(
    tmp_path: Path,
    subcommand_responses: Optional[dict[str, str]] = None,
) -> tuple[str, str]:
    """Write a stub ``mpm`` executable that records calls and returns fixture output.

    The stub handles ``mpm <subcommand> [args...]`` calls.  Each
    ``subcommand_responses`` key is a subcommand name; its value is the
    newline-delimited stdout the stub should emit for that subcommand.

    Args:
        tmp_path: Temporary directory used for the stub and call log.
        subcommand_responses: Mapping from subcommand name to fixture output.

    Returns:
        Tuple of (stub_bin_dir, call_log_path).  ``stub_bin_dir`` must be
        prepended to ``PATH`` before sourcing the completion script.
    """
    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"

    case_branches = ""
    if subcommand_responses:
        for subcmd, output in subcommand_responses.items():
            out_file = tmp_path / f"out_{subcmd.lstrip('_')}.txt"
            out_file.write_text(output, encoding="utf-8")
            case_branches += f'        "{subcmd}") cat {out_file} ;;\n'

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        # Stub mpm: records invocations, returns configured fixture output.
        printf '%s\\n' "$*" >> {call_log}
        subcommand="${{1:-}}"
        case "$subcommand" in
        {case_branches}
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return str(stub_dir), str(call_log)


def _bash_completion_runner(
    tmp_path: Path,
    comp_line: str,
    comp_words: list[str],
    comp_cword: int,
    stub_bin_dir: Optional[str] = None,
    extra_env: Optional[dict[str, str]] = None,
) -> list[str]:
    """Source the live completion script and return COMPREPLY from ``_shtab_mpm``.

    This fixture is reused by every parametrized static-row case (AC-TEST-002).
    It:
    1. Captures the live ``mpm completion bash`` output and writes it to a
       temp file.
    2. Verifies the script parses cleanly under ``bash -n`` (AC-FUNC-007).
    3. Spawns ``bash -c`` that sources the script, sets the COMP_* env,
       calls ``_shtab_mpm``, and prints each COMPREPLY item prefixed with
       ``CANDIDATE:``.
    4. Returns the list of printed items.

    Args:
        tmp_path: Temporary directory for the completion script and outputs.
        comp_line: Full command line as the user typed it (``COMP_LINE``).
        comp_words: Tokenized words (``COMP_WORDS``).
        comp_cword: Index of the word being completed (``COMP_CWORD``).
        stub_bin_dir: Optional directory prepended to ``PATH`` for stub mpm.
        extra_env: Optional additional environment variables for the subprocess.

    Returns:
        Sorted list of completion candidates from ``COMPREPLY``.
    """
    script_content = _mpm_completion_script()
    _bash_syntax_check(script_content)

    completion_file = tmp_path / "mpm_completion.bash"
    completion_file.write_text(script_content, encoding="utf-8")

    comp_words_bash = " ".join(f'"{w}"' for w in comp_words)
    path_prefix = f'"{stub_bin_dir}":' if stub_bin_dir else ""

    bash_script = textwrap.dedent(f"""\
        export PATH={path_prefix}"$PATH"
        source {completion_file}
        COMP_LINE={comp_line!r}
        COMP_WORDS=({comp_words_bash})
        COMP_CWORD={comp_cword}
        COMP_POINT=${{#COMP_LINE}}
        _shtab_mpm
        for item in "${{COMPREPLY[@]}}"; do
            printf 'CANDIDATE:%s\\n' "$item"
        done
        """)

    merged_env = {**os.environ, **(extra_env or {})}
    result = subprocess.run(
        ["bash", "-c", bash_script],
        capture_output=True,
        text=True,
        env=merged_env,
    )
    assert result.returncode == 0, (
        f"Bash completion script failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    candidates = [line[len("CANDIDATE:") :] for line in result.stdout.splitlines() if line.startswith("CANDIDATE:")]
    return sorted(candidates)


def _bash_preamble_runner(
    tmp_path: Path,
    helper_call: str,
    stub_bin_dir: Optional[str] = None,
    extra_env: Optional[dict[str, str]] = None,
) -> list[str]:
    """Source the live completion script and call a preamble helper directly.

    Used for DYNAMIC rows where the completion is invoked through the preamble
    helper functions (e.g., ``_mpm_complete_catalog_entries``) rather than
    through ``_shtab_mpm``'s COMPGEN dispatch.

    This fixture is reused by every parametrized dynamic-row case (AC-TEST-002).
    It:
    1. Captures the live ``mpm completion bash`` output and writes it to a
       temp file.
    2. Verifies the script parses cleanly under ``bash -n`` (AC-FUNC-007).
    3. Spawns ``bash -c`` that sources the script, initialises COMPREPLY,
       calls the specified helper, and prints each COMPREPLY item prefixed
       with ``CANDIDATE:``.
    4. Returns the list of printed items.

    Args:
        tmp_path: Temporary directory for the completion script.
        helper_call: Bash expression to call the preamble helper, e.g.
            ``'_mpm_complete_catalog_entries ""'``.
        stub_bin_dir: Optional directory prepended to ``PATH`` for stub mpm.
        extra_env: Optional additional environment variables.

    Returns:
        Sorted list of completion candidates from ``COMPREPLY``.
    """
    script_content = _mpm_completion_script()
    _bash_syntax_check(script_content)

    completion_file = tmp_path / "mpm_completion.bash"
    completion_file.write_text(script_content, encoding="utf-8")

    path_prefix = f'"{stub_bin_dir}":' if stub_bin_dir else ""

    bash_script = textwrap.dedent(f"""\
        export PATH={path_prefix}"$PATH"
        source {completion_file}
        COMPREPLY=()
        {helper_call}
        for item in "${{COMPREPLY[@]}}"; do
            printf 'CANDIDATE:%s\\n' "$item"
        done
        """)

    merged_env = {**os.environ, **(extra_env or {})}
    result = subprocess.run(
        ["bash", "-c", bash_script],
        capture_output=True,
        text=True,
        env=merged_env,
    )
    assert result.returncode == 0, (
        f"Bash preamble helper script failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    candidates = [line[len("CANDIDATE:") :] for line in result.stdout.splitlines() if line.startswith("CANDIDATE:")]
    return sorted(candidates)


@pytest.mark.integration
def test_bash_version_gte_4() -> None:
    """AC-FUNC-006: bash >= 4.0 is available; fail with actionable error if not."""
    _assert_bash_version_gte_4()


@pytest.mark.integration
def test_completion_script_syntax_valid() -> None:
    """AC-FUNC-007: live completion script passes ``bash -n`` before any test case."""
    script = _mpm_completion_script()
    _bash_syntax_check(script)


_STATIC_ROWS: list[tuple[str, str, list[str], int, list[str], bool]] = [
    (
        "global_flags",
        "mpm --",
        ["mpm", "--"],
        1,
        [
            "--help",
            "--version",
            "--quiet",
            "--verbose",
            "--no-color",
            "--no-update-check",
            "--home",
            "--store-dir",
        ],
        True,
    ),
    (
        "top_level_subcommands",
        "mpm ",
        ["mpm", ""],
        1,
        [
            "add",
            "catalog",
            "clean",
            "completion",
            "doctor",
            "install",
            "marketplace",
            "search",
            "outdated",
            "remove",
            "validate",
            "repo",
            "why",
        ],
        False,
    ),
    (
        "completion_shell_enum",
        "mpm completion ",
        ["mpm", "completion", ""],
        2,
        ["bash", "zsh", "powershell"],
        True,
    ),
    (
        "search_format_enum",
        "mpm search --format ",
        ["mpm", "search", "--format", ""],
        3,
        ["names", "json"],
        True,
    ),
    (
        "search_flags",
        "mpm search --",
        ["mpm", "search", "--"],
        2,
        ["--help", "--format", "--detail", "--tree", "--all", "--no-limit", "--no-filter-required"],
        False,
    ),
    (
        "search_match_fields_flag_present",
        "mpm search --",
        ["mpm", "search", "--"],
        2,
        ["--match-fields"],
        False,
    ),
    (
        "search_since_version_flag_present",
        "mpm search --",
        ["mpm", "search", "--"],
        2,
        ["--since-version"],
        False,
    ),
    (
        "search_regex_flag_present",
        "mpm search --",
        ["mpm", "search", "--"],
        2,
        ["--regex"],
        False,
    ),
    (
        "outdated_format_enum",
        "mpm outdated --format ",
        ["mpm", "outdated", "--format", ""],
        3,
        ["table", "json"],
        True,
    ),
    (
        "outdated_flags",
        "mpm outdated --",
        ["mpm", "outdated", "--"],
        2,
        ["--help", "--format", "--fail-on-upgrade"],
        False,
    ),
    (
        "outdated_filesystem_flags",
        "mpm outdated --",
        ["mpm", "outdated", "--"],
        2,
        ["--mpm-file", "--lock-file"],
        False,
    ),
    (
        "why_format_enum",
        "mpm why --format ",
        ["mpm", "why", "--format", ""],
        3,
        ["text", "json"],
        True,
    ),
    (
        "why_flags",
        "mpm why --",
        ["mpm", "why", "--"],
        2,
        ["--help", "--format", "--mpm-file", "--lock-file"],
        False,
    ),
    (
        "catalog_subcommand_enum",
        "mpm catalog ",
        ["mpm", "catalog", ""],
        2,
        ["audit"],
        True,
    ),
    (
        "catalog_audit_format_enum",
        "mpm catalog audit --format ",
        ["mpm", "catalog", "audit", "--format", ""],
        4,
        ["text", "json"],
        True,
    ),
    (
        "catalog_audit_flags",
        "mpm catalog audit --",
        ["mpm", "catalog", "audit", "--"],
        3,
        ["--check", "--format", "--strict"],
        False,
    ),
    (
        "validate_subcommand_enum",
        "mpm validate ",
        ["mpm", "validate", ""],
        2,
        ["xml", "marketplace", "metadata", "lockfile"],
        True,
    ),
    (
        "validate_metadata_format_enum",
        "mpm validate metadata --format ",
        ["mpm", "validate", "metadata", "--format", ""],
        4,
        ["text", "json"],
        True,
    ),
    (
        "add_flags",
        "mpm add --",
        ["mpm", "add", "--"],
        2,
        ["--help", "--force", "--dry-run", "--mpm-file"],
        False,
    ),
    (
        "add_catalog_source_flag",
        "mpm add --",
        ["mpm", "add", "--"],
        2,
        ["--catalog-source"],
        False,
    ),
    (
        "remove_flags",
        "mpm remove --",
        ["mpm", "remove", "--"],
        2,
        ["--help", "--force", "--dry-run", "--mpm-file"],
        False,
    ),
    (
        "install_flags_no_value",
        "mpm install --",
        ["mpm", "install", "--"],
        2,
        ["--help", "--refresh-lock", "--strict-lock", "--strict-drift"],
        False,
    ),
    (
        "install_lock_file_flag_present",
        "mpm install --",
        ["mpm", "install", "--"],
        2,
        ["--lock-file"],
        False,
    ),
    (
        "install_refresh_lock_source_flag_present",
        "mpm install --",
        ["mpm", "install", "--"],
        2,
        ["--refresh-lock-source"],
        False,
    ),
    (
        "doctor_flags",
        "mpm doctor --",
        ["mpm", "doctor", "--"],
        2,
        ["--help", "--refresh-completion-cache", "--strict-drift", "--prune-cache"],
        False,
    ),
    (
        "doctor_filesystem_flags",
        "mpm doctor --",
        ["mpm", "doctor", "--"],
        2,
        ["--mpm-file", "--lock-file"],
        False,
    ),
    (
        "validate_xml_repo_root_flag",
        "mpm validate xml --",
        ["mpm", "validate", "xml", "--"],
        3,
        ["--repo-root"],
        False,
    ),
    (
        "validate_marketplace_repo_root_flag",
        "mpm validate marketplace --",
        ["mpm", "validate", "marketplace", "--"],
        3,
        ["--repo-root"],
        False,
    ),
    (
        "validate_metadata_repo_root_flag",
        "mpm validate metadata --",
        ["mpm", "validate", "metadata", "--"],
        3,
        ["--repo-root"],
        False,
    ),
    (
        "clean_flags",
        "mpm clean --",
        ["mpm", "clean", "--"],
        2,
        ["--help"],
        False,
    ),
    (
        "repo_repo_dir_flag",
        "mpm repo --",
        ["mpm", "repo", "--"],
        2,
        ["--repo-dir"],
        False,
    ),
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "test_id,comp_line,comp_words,comp_cword,expected,exact_match",
    [pytest.param(*row, id=row[0]) for row in _STATIC_ROWS],
)
def test_static_completion_row(
    tmp_path: Path,
    test_id: str,
    comp_line: str,
    comp_words: list[str],
    comp_cword: int,
    expected: list[str],
    exact_match: bool,
) -> None:
    """AC-FUNC-002: static-enum rows return the expected candidate set via _shtab_mpm.

    For each row: set COMP_LINE/COMP_WORDS/COMP_CWORD, invoke _shtab_mpm,
    assert COMPREPLY matches or contains the expected candidates.
    """
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line=comp_line,
        comp_words=comp_words,
        comp_cword=comp_cword,
    )
    if exact_match:
        assert sorted(candidates) == sorted(expected), (
            f"[{test_id}] Expected exact COMPREPLY={sorted(expected)!r}, got {sorted(candidates)!r}"
        )
    else:
        missing = [c for c in expected if c not in candidates]
        assert not missing, (
            f"[{test_id}] Expected COMPREPLY to contain {expected!r}, "
            f"but missing {missing!r}. Got: {sorted(candidates)!r}"
        )


@pytest.mark.integration
def test_bootstrap_offers_no_bootstrap_specific_flag_completion(tmp_path: Path) -> None:
    """`mpm bootstrap --<TAB>` offers no bootstrap-specific flag candidates.

    bootstrap was removed in a major release and is no longer a registered
    subcommand. Completion at `mpm bootstrap --` therefore falls through to
    the top-level parser and offers only the global flags; the old
    `--output-dir`/`--catalog-source` bootstrap completions are gone.
    """
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line="mpm bootstrap --",
        comp_words=["mpm", "bootstrap", "--"],
        comp_cword=2,
    )
    flag_candidates = [c for c in candidates if c.startswith("-")]
    assert "--output-dir" not in flag_candidates, (
        f"bootstrap-specific '--output-dir' completion must be gone, got: {flag_candidates!r}"
    )
    assert "--catalog-source" not in flag_candidates, (
        f"bootstrap-specific '--catalog-source' completion must be gone, got: {flag_candidates!r}"
    )


def _assert_stub_called_with(call_log_path: str, expected_subcommand: str, expected_token: Optional[str]) -> None:
    """Assert the stub mpm was invoked with the expected subcommand and token."""
    call_log = Path(call_log_path)
    assert call_log.exists(), (
        f"Stub call log not found at {call_log_path!r}; did the completion script invoke mpm {expected_subcommand!r}?"
    )
    calls = call_log.read_text(encoding="utf-8").strip()
    assert expected_subcommand in calls, (
        f"Expected stub to be called with subcommand {expected_subcommand!r}, got call log: {calls!r}"
    )
    if expected_token is not None:
        assert expected_token in calls, f"Expected token {expected_token!r} in stub call log, got: {calls!r}"


@pytest.mark.integration
def test_dynamic_row_add_catalog_entries(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm add <TAB>' -- preamble helper routes to catalog entries.

    Sources the live completion script, invokes _mpm_complete_catalog_entries
    via the stub mpm, and asserts (a) stub called with
    __complete_catalog_entries and (b) COMPREPLY equals fixture output.
    """
    _assert_bash_version_gte_4()
    fixture_entries = "my-tool\nanother-entry\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["my-tool", "another-entry"]), (
        f"Expected COMPREPLY=['my-tool','another-entry'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries", None)


@pytest.mark.integration
def test_dynamic_row_bootstrap_catalog_entries(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm bootstrap <TAB>' -- preamble helper routes to catalog entries.

    Section 11.2: bootstrap retains catalog-entry completion for the
    deprecation window via the same _mpm_complete_catalog_entries helper.
    """
    _assert_bash_version_gte_4()
    fixture_entries = "legacy-pkg\nold-tool\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["legacy-pkg", "old-tool"]), (
        f"Expected COMPREPLY=['legacy-pkg','old-tool'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries", None)


@pytest.mark.integration
def test_dynamic_row_remove_source_names(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm remove <TAB>' -- preamble routes to source_names_in_mpm."""
    _assert_bash_version_gte_4()
    fixture_entries = "source-alpha\nsource-beta\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_source_names_in_mpm": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_source_names_in_mpm ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["source-alpha", "source-beta"]), (
        f"Expected COMPREPLY=['source-alpha','source-beta'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_source_names_in_mpm", None)


@pytest.mark.integration
def test_dynamic_row_install_refresh_lock_source(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm install --refresh-lock-source <TAB>' routes to source_names."""
    _assert_bash_version_gte_4()
    fixture_entries = "src-one\nsrc-two\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_source_names_in_mpm": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_source_names_in_mpm ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["src-one", "src-two"]), (
        f"Expected COMPREPLY=['src-one','src-two'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_source_names_in_mpm", None)


@pytest.mark.integration
def test_dynamic_row_why_lockfile_names(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm why <TAB>' -- preamble routes to names_in_lockfile."""
    _assert_bash_version_gte_4()
    fixture_entries = "locked-entry\nhttps://example.com/repo.git\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_names_in_lockfile": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_names_in_lockfile ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["locked-entry", "https://example.com/repo.git"]), (
        f"Expected lockfile names in COMPREPLY, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_names_in_lockfile", None)


@pytest.mark.integration
def test_dynamic_row_global_catalog_source(tmp_path: Path) -> None:
    """AC-FUNC-003: '--catalog-source <TAB>' -- preamble routes to cached_catalogs."""
    _assert_bash_version_gte_4()
    fixture_entries = "https://catalog.example.com/repo.git@main\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_cached_catalogs": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_cached_catalogs ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert candidates == ["https://catalog.example.com/repo.git@main"], (
        f"Expected cached catalog URL in COMPREPLY, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_cached_catalogs", None)


@pytest.mark.integration
def test_dynamic_row_list_since_version(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm search --since-version <TAB>' routes to catalog_versions."""
    _assert_bash_version_gte_4()
    fixture_entries = "1.0.0\n2.0.0\n3.0.0\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_versions": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_versions ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == ["1.0.0", "2.0.0", "3.0.0"], f"Expected version list in COMPREPLY, got {candidates!r}"
    _assert_stub_called_with(call_log_path, "__complete_catalog_versions", None)


@pytest.mark.integration
def test_dynamic_row_add_no_at_routes_catalog(tmp_path: Path) -> None:
    """AC-FUNC-004 (no-@ path): 'mpm add my-t<TAB>' routes to catalog entries.

    _mpm_complete_add_arg without @ in the token delegates to
    _mpm_complete_catalog_entries.  The stub must be invoked with
    __complete_catalog_entries and the token 'my-t'.
    """
    _assert_bash_version_gte_4()
    fixture_entries = "my-tool\nmy-toolbox\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'my-t'",
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["my-tool", "my-toolbox"]), (
        f"Expected catalog entries for no-@ token, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries", "my-t")


@pytest.mark.integration
def test_dynamic_row_add_with_at_routes_project_versions(tmp_path: Path) -> None:
    """AC-FUNC-004 (with-@ path): 'mpm add foo@<TAB>' resolves repo URL then lists versions.

    _mpm_complete_add_arg detects the '@' separator, shells out to
    mpm __resolve_entry_to_repo_url foo to get the repo URL, then calls
    _mpm_complete_project_versions with that URL and the empty spec.
    COMPREPLY must contain the project versions returned by the stub.
    """
    _assert_bash_version_gte_4()

    repo_url = "https://example.com/foo.git"
    versions_output = "1.0.0\n2.0.0\n"

    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"

    resolve_out = tmp_path / "out_resolve.txt"
    resolve_out.write_text(repo_url + "\n", encoding="utf-8")
    versions_out = tmp_path / "out_versions.txt"
    versions_out.write_text(versions_output, encoding="utf-8")

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        # Stub mpm: supports __resolve_entry_to_repo_url and
        # __complete_project_versions.
        printf '%s\\n' "$*" >> {call_log}
        subcommand="${{1:-}}"
        case "$subcommand" in
            "__resolve_entry_to_repo_url") cat {resolve_out} ;;
            "__complete_project_versions") cat {versions_out} ;;
            "__complete_catalog_entries") ;;
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'foo@'",
        stub_bin_dir=str(stub_dir),
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )

    assert "1.0.0" in candidates, f"Expected '1.0.0' in COMPREPLY for 'foo@' completion, got {candidates!r}"
    assert "2.0.0" in candidates, f"Expected '2.0.0' in COMPREPLY for 'foo@' completion, got {candidates!r}"

    call_log_text = Path(call_log).read_text(encoding="utf-8") if Path(call_log).exists() else ""
    assert "__resolve_entry_to_repo_url" in call_log_text, (
        f"Expected __resolve_entry_to_repo_url call for 'foo@', got: {call_log_text!r}"
    )
    assert "__complete_project_versions" in call_log_text, (
        f"Expected __complete_project_versions call for 'foo@', got: {call_log_text!r}"
    )


_DYNAMIC_DISABLED_CASES: list[tuple[str, str, str]] = [
    (
        "catalog_entries_disabled",
        '_mpm_complete_catalog_entries ""',
        "__complete_catalog_entries",
    ),
    (
        "source_names_disabled",
        '_mpm_complete_source_names_in_mpm ""',
        "__complete_source_names_in_mpm",
    ),
    (
        "lockfile_names_disabled",
        '_mpm_complete_names_in_lockfile ""',
        "__complete_names_in_lockfile",
    ),
    (
        "catalog_versions_disabled",
        '_mpm_complete_catalog_versions ""',
        "__complete_catalog_versions",
    ),
    (
        "cached_catalogs_disabled",
        '_mpm_complete_cached_catalogs ""',
        "__complete_cached_catalogs",
    ),
    (
        "add_arg_disabled",
        "_mpm_complete_add_arg 'my-entry'",
        "__complete_catalog_entries",
    ),
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "test_id,helper_call,stub_subcommand",
    [pytest.param(*row, id=row[0]) for row in _DYNAMIC_DISABLED_CASES],
)
def test_mpm_completion_enabled_0_returns_empty(
    tmp_path: Path,
    test_id: str,
    helper_call: str,
    stub_subcommand: str,
) -> None:
    """AC-FUNC-005: MPM_COMPLETION_ENABLED=0 causes dynamic helpers to return empty COMPREPLY.

    The stub must NOT be invoked when MPM_COMPLETION_ENABLED=0.
    """
    _assert_bash_version_gte_4()
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {stub_subcommand: "fixture-entry\n"})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call=helper_call,
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "0"},
    )
    assert candidates == [], f"[{test_id}] Expected empty COMPREPLY when MPM_COMPLETION_ENABLED=0, got {candidates!r}"
    call_log = Path(call_log_path)
    if call_log.exists():
        calls = call_log.read_text(encoding="utf-8").strip()
        assert calls == "", (
            f"[{test_id}] Stub must not be invoked when MPM_COMPLETION_ENABLED=0, but got calls: {calls!r}"
        )


@pytest.mark.integration
def test_ac_cycle_001_search_format(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm search --format <TAB> => (names, json)."""
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line="mpm search --format ",
        comp_words=["mpm", "search", "--format", ""],
        comp_cword=3,
    )
    assert sorted(candidates) == ["json", "names"], f"AC-CYCLE-001: expected (names json), got {candidates!r}"


@pytest.mark.integration
def test_ac_cycle_001_completion_shell(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm completion <TAB> => (bash, zsh, powershell)."""
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line="mpm completion ",
        comp_words=["mpm", "completion", ""],
        comp_cword=2,
    )
    assert sorted(candidates) == ["bash", "powershell", "zsh"], (
        f"AC-CYCLE-001: expected (bash powershell zsh), got {candidates!r}"
    )


@pytest.mark.integration
def test_ac_cycle_001_outdated_format(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm outdated --format <TAB> => (table, json)."""
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line="mpm outdated --format ",
        comp_words=["mpm", "outdated", "--format", ""],
        comp_cword=3,
    )
    assert sorted(candidates) == ["json", "table"], f"AC-CYCLE-001: expected (table json), got {candidates!r}"


@pytest.mark.integration
def test_ac_cycle_001_validate_subcommands(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm validate <TAB> => (xml, marketplace, metadata, lockfile)."""
    _assert_bash_version_gte_4()
    candidates = _bash_completion_runner(
        tmp_path=tmp_path,
        comp_line="mpm validate ",
        comp_words=["mpm", "validate", ""],
        comp_cword=2,
    )
    assert sorted(candidates) == ["lockfile", "marketplace", "metadata", "xml"], (
        f"AC-CYCLE-001: expected (xml marketplace metadata lockfile), got {candidates!r}"
    )


@pytest.mark.integration
def test_ac_cycle_001_dynamic_add_with_stub(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm add <TAB> with stub returns fixture entries.

    Steps:
    1. Write stub mpm returning 'my-tool' for __complete_catalog_entries.
    2. Source the live completion script (passes bash -n check).
    3. Invoke _mpm_complete_catalog_entries (the preamble helper for 'add').
    4. Assert COMPREPLY contains 'my-tool' and 'other-pkg'.
    """
    _assert_bash_version_gte_4()
    stub_bin_dir, _call_log = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": "my-tool\nother-pkg\n"})
    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert "my-tool" in candidates, f"AC-CYCLE-001: expected 'my-tool' in COMPREPLY, got {candidates!r}"
    assert "other-pkg" in candidates, f"AC-CYCLE-001: expected 'other-pkg' in COMPREPLY, got {candidates!r}"


@pytest.mark.integration
def test_ac_cycle_001_add_at_spec(tmp_path: Path) -> None:
    """AC-CYCLE-001: end-to-end -- mpm add foo@ routes to project versions.

    Sources the live completion script; _mpm_complete_add_arg 'foo@'
    resolves the repo URL via the stub and returns version candidates.
    """
    _assert_bash_version_gte_4()

    repo_url = "https://example.com/foo.git"
    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"
    resolve_out = tmp_path / "resolve.txt"
    resolve_out.write_text(repo_url + "\n", encoding="utf-8")
    versions_out = tmp_path / "versions.txt"
    versions_out.write_text("1.0.0\n2.0.0\n", encoding="utf-8")

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        printf '%s\\n' "$*" >> {call_log}
        case "${{1:-}}" in
            "__resolve_entry_to_repo_url") cat {resolve_out} ;;
            "__complete_project_versions") cat {versions_out} ;;
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    candidates = _bash_preamble_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'foo@'",
        stub_bin_dir=str(stub_dir),
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert "1.0.0" in candidates, f"AC-CYCLE-001: expected '1.0.0' in COMPREPLY, got {candidates!r}"
    assert "2.0.0" in candidates, f"AC-CYCLE-001: expected '2.0.0' in COMPREPLY, got {candidates!r}"
