"""Integration tests for zsh shell completion via _shtab_mpm (_main_complete).

Implements Section 11.9 acceptance item 1 and 6: every row in the Section 11.2
completion-coverage matrix has a passing integration test asserting the
expected candidate list.

Each parametrized case corresponds to one row of Section 11.2.  The test
runner sources the live ``mpm completion zsh`` output into a real zsh
process (>= 5.0).

For STATIC rows (choices-based flags and subcommand enums), the test inspects
the option spec arrays declared by the generated zsh completion script and
the subcommand-listing helper functions (e.g., ``_shtab_mpm_commands``).
These arrays ARE the source of truth for what ``_arguments`` will offer.

For DYNAMIC rows, the test calls the preamble helper functions directly
(e.g., ``_mpm_complete_catalog_entries``, ``_mpm_complete_add_arg``).
The preamble helpers are defined in the completion script generated by
``mpm completion zsh`` and are available after sourcing that script.
The test places a stub ``mpm`` executable on ``$PATH`` and asserts:
  (a) the stub was invoked exactly once with the expected subcommand and
      ``<current-token>`` argument, and
  (b) ``compadd`` was called with the stub's output.

AC-FUNC-008 -- zsh availability check -- is an assertion (not a skip) so the
suite fails loudly when zsh is not installed.

AC-FUNC-007 -- the generated completion script is validated with ``zsh -n``
before every parametrized case.

AC-FUNC-004 -- the generated script starts with ``#compdef mpm``.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path
from typing import Optional

import pytest


pytestmark = pytest.mark.skipif(
    shutil.which("zsh") is None,
    reason="zsh is not installed; zsh completion is validated on POSIX runners",
)


def _assert_zsh_available() -> None:
    """Assert zsh is available on PATH; fail with actionable message if not.

    AC-FUNC-008: This is NOT a skip -- a missing zsh environment means the
    completion system will not function and is a test infrastructure failure.
    """
    result = subprocess.run(["which", "zsh"], capture_output=True, text=True)
    assert result.returncode == 0, (
        "zsh is not available on PATH -- cannot run zsh completion integration tests. "
        "Install zsh via your package manager: 'apt-get install zsh' (Debian/Ubuntu), "
        "'yum install zsh' (RHEL/CentOS), or 'brew install zsh' (macOS)."
    )


def _mpm_completion_script() -> str:
    """Return the live ``mpm completion zsh`` output."""
    result = subprocess.run(
        [sys.executable, "-m", "mpm_cli", "completion", "zsh"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"mpm completion zsh failed with exit {result.returncode}. stderr: {result.stderr!r}"
    assert result.stdout.strip(), "mpm completion zsh produced empty output"
    return result.stdout


def _zsh_syntax_check(script_content: str) -> None:
    """Assert that ``script_content`` is valid zsh syntax via ``zsh -n``."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".zsh", delete=False) as tmp:
        tmp.write(script_content)
        tmp_path = tmp.name
    try:
        check = subprocess.run(["zsh", "-n", tmp_path], capture_output=True, text=True)
        assert check.returncode == 0, f"zsh -n syntax check failed.\nstderr: {check.stderr!r}"
    finally:
        os.unlink(tmp_path)


def _write_completion_file(tmp_path: Path) -> str:
    """Write the live completion script to a temp file and return the path."""
    script_content = _mpm_completion_script()
    _zsh_syntax_check(script_content)
    completion_file = tmp_path / "mpm_completion.zsh"
    completion_file.write_text(script_content, encoding="utf-8")
    return str(completion_file)


def _write_stub_mpm(
    tmp_path: Path,
    subcommand_responses: Optional[dict[str, str]] = None,
) -> tuple[str, str]:
    """Write a stub ``mpm`` executable that records calls and returns fixture output.

    The stub handles ``mpm <subcommand> [args...]`` calls.  Each
    ``subcommand_responses`` key is a subcommand name; its value is the
    newline-delimited stdout the stub should emit for that subcommand.

    Args:
        tmp_path: Temporary directory used for the stub and call log.
        subcommand_responses: Mapping from subcommand name to fixture output.

    Returns:
        Tuple of (stub_bin_dir, call_log_path).  ``stub_bin_dir`` must be
        prepended to ``PATH`` before sourcing the completion script.
    """
    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"

    case_branches = ""
    if subcommand_responses:
        for subcmd, output in subcommand_responses.items():
            out_file = tmp_path / f"out_{subcmd.lstrip('_')}.txt"
            out_file.write_text(output, encoding="utf-8")
            case_branches += f'        "{subcmd}") cat {out_file} ;;\n'

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        # Stub mpm: records invocations, returns configured fixture output.
        printf '%s\\n' "$*" >> {call_log}
        subcommand="${{1:-}}"
        case "$subcommand" in
        {case_branches}
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return str(stub_dir), str(call_log)


def _zsh_completion_runner(
    tmp_path: Path,
    helper_call: str,
    stub_bin_dir: Optional[str] = None,
    extra_env: Optional[dict[str, str]] = None,
) -> list[str]:
    """Source the live completion script and capture ``compadd`` candidates.

    This is the central fixture reused by every parametrized dynamic-row case
    (AC-TEST-002).  It:
    1. Captures the live ``mpm completion zsh`` output and writes it to a
       temp file.
    2. Verifies the script parses cleanly under ``zsh -n`` (AC-FUNC-007).
    3. Spawns ``zsh -fc`` that overrides ``compadd`` and ``_arguments`` to
       capture candidates, sources the completion script, and invokes the
       specified helper expression.
    4. Returns the list of captured candidate items.

    ``compadd`` is overridden to collect all non-flag arguments.
    ``_arguments`` is overridden with a no-op so that sourcing the script
    succeeds outside a real completion context (zsh's ``_arguments`` can only
    run inside a completion function).

    Args:
        tmp_path: Temporary directory for the completion script and outputs.
        helper_call: Zsh expression to invoke, e.g.
            ``'_mpm_complete_catalog_entries ""'``.
        stub_bin_dir: Optional directory prepended to ``PATH`` for stub mpm.
        extra_env: Optional additional environment variables for the subprocess.

    Returns:
        Sorted list of completion candidates captured from ``compadd``.
    """
    completion_file = _write_completion_file(tmp_path)
    path_prefix = f'"{stub_bin_dir}":' if stub_bin_dir else ""

    zsh_script = textwrap.dedent(f"""\
        export PATH={path_prefix}"$PATH"
        # Override _arguments: no-op so sourcing works outside completion context.
        _arguments() {{ return 0; }}
        # Override compdef: no-op registration.
        compdef() {{ return 0; }}
        # Override compadd: capture non-flag arguments as candidates.
        _captured_completions=()
        compadd() {{
            local saw_dashdash=0
            for arg in "$@"; do
                if [[ "$arg" == "--" ]]; then
                    saw_dashdash=1
                    continue
                fi
                if [[ $saw_dashdash -eq 1 ]]; then
                    [[ -n "$arg" ]] && _captured_completions+=("$arg")
                fi
            done
        }}
        source {completion_file}
        {helper_call}
        for item in "${{_captured_completions[@]}}"; do
            printf 'CANDIDATE:%s\\n' "$item"
        done
        """)

    merged_env = {**os.environ, **(extra_env or {})}
    result = subprocess.run(
        ["zsh", "-fc", zsh_script],
        capture_output=True,
        text=True,
        env=merged_env,
    )
    assert result.returncode == 0, (
        f"Zsh completion script failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    candidates = [line[len("CANDIDATE:") :] for line in result.stdout.splitlines() if line.startswith("CANDIDATE:")]
    return sorted(candidates)


def _zsh_option_spec_runner(
    tmp_path: Path,
    option_array_name: str,
    label: str,
) -> list[str]:
    """Extract enum choices from a zsh option spec array by label.

    Sources the completion script with mocked ``_arguments`` and ``compdef``,
    then inspects the named option spec array for a spec element whose label
    matches ``label``.  Parses the parenthesised choice list and returns it.

    For example, ``_shtab_mpm_search_options`` contains a spec like::

        "--format[...]:list_format:(names json)"

    Calling this with ``label="list_format"`` returns ``["json", "names"]``.

    Args:
        tmp_path: Temporary directory for the completion script.
        option_array_name: Name of the zsh array to inspect, e.g.
            ``"_shtab_mpm_search_options"``.
        label: The positional-argument label to match, e.g. ``"list_format"``.

    Returns:
        Sorted list of choices extracted from the spec.
    """
    completion_file = _write_completion_file(tmp_path)

    zsh_script = textwrap.dedent(f"""\
        _arguments() {{ return 0; }}
        compdef() {{ return 0; }}
        _describe() {{ return 0; }}
        source {completion_file}
        local varname="{option_array_name}"
        local -a arr
        arr=("${{(@P)varname}}")
        for opt in "${{arr[@]}}"; do
            if [[ "$opt" == *":{label}:"* ]]; then
                local rest="${{opt##*:{label}:}}"
                # Strip surrounding parentheses
                rest="${{rest:1:-1}}"
                for choice in ${{=rest}}; do
                    printf 'CHOICE:%s\\n' "$choice"
                done
                break
            fi
        done
        """)

    result = subprocess.run(
        ["zsh", "-fc", zsh_script],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Zsh option spec extraction failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    choices = [line[len("CHOICE:") :] for line in result.stdout.splitlines() if line.startswith("CHOICE:")]
    return sorted(choices)


def _zsh_positional_spec_runner(
    tmp_path: Path,
    option_array_name: str,
    pattern: str,
) -> list[str]:
    """Extract enum choices from a positional spec element matching a pattern.

    Used for specs like ``:Target shell. Choices\\: \\{bash, zsh\\}.:(bash zsh)``
    where the label field is blank (positional).  Matches any spec element
    that contains ``pattern`` and ends with a parenthesised choice list.

    Args:
        tmp_path: Temporary directory for the completion script.
        option_array_name: Name of the zsh array to inspect.
        pattern: Substring to match within the spec element, e.g.
            ``"bash zsh"`` or ``"bash, zsh"``.

    Returns:
        Sorted list of choices parsed from the matching spec element.
    """
    completion_file = _write_completion_file(tmp_path)

    zsh_script = textwrap.dedent(f"""\
        _arguments() {{ return 0; }}
        compdef() {{ return 0; }}
        _describe() {{ return 0; }}
        source {completion_file}
        local varname="{option_array_name}"
        local -a arr
        arr=("${{(@P)varname}}")
        for opt in "${{arr[@]}}"; do
            if [[ "$opt" == *"{pattern}"* ]]; then
                # Find the last colon-paren group "(choices)" in the spec
                local rest="${{opt##*:}}"
                if [[ "$rest" == "("* ]]; then
                    rest="${{rest:1:-1}}"
                    for choice in ${{=rest}}; do
                        printf 'CHOICE:%s\\n' "$choice"
                    done
                    break
                fi
            fi
        done
        """)

    result = subprocess.run(
        ["zsh", "-fc", zsh_script],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Zsh positional spec extraction failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    choices = [line[len("CHOICE:") :] for line in result.stdout.splitlines() if line.startswith("CHOICE:")]
    return sorted(choices)


def _zsh_subcommand_runner(
    tmp_path: Path,
    commands_fn: str,
) -> list[str]:
    """Capture subcommand names emitted by a ``_shtab_*_commands`` function.

    Sources the completion script with mocked ``_arguments`` and ``compdef``,
    overrides ``_describe`` to extract the subcommand names from the local
    ``_commands`` array, then calls the specified function.

    Args:
        tmp_path: Temporary directory for the completion script.
        commands_fn: Name of the commands function to call, e.g.
            ``"_shtab_mpm_commands"``.

    Returns:
        Sorted list of subcommand names.
    """
    completion_file = _write_completion_file(tmp_path)

    zsh_script = textwrap.dedent(f"""\
        _arguments() {{ return 0; }}
        compdef() {{ return 0; }}
        _describe() {{
            local tag="$1"
            local inner_arr_name="$2"
            local -a inner_arr
            inner_arr=("${{(@P)inner_arr_name}}")
            for item in "${{inner_arr[@]}}"; do
                printf 'SUBCOMMAND:%s\\n' "${{item%%:*}}"
            done
        }}
        source {completion_file}
        {commands_fn}
        """)

    result = subprocess.run(
        ["zsh", "-fc", zsh_script],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Zsh subcommand runner failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    subcommands = [line[len("SUBCOMMAND:") :] for line in result.stdout.splitlines() if line.startswith("SUBCOMMAND:")]
    return sorted(subcommands)


def _assert_stub_called_with(
    call_log_path: str,
    expected_subcommand: str,
    expected_token: Optional[str] = None,
) -> None:
    """Assert the stub mpm was invoked with the expected subcommand and token."""
    call_log = Path(call_log_path)
    assert call_log.exists(), (
        f"Stub call log not found at {call_log_path!r}; did the completion script invoke mpm {expected_subcommand!r}?"
    )
    calls = call_log.read_text(encoding="utf-8").strip()
    assert expected_subcommand in calls, (
        f"Expected stub to be called with subcommand {expected_subcommand!r}, got call log: {calls!r}"
    )
    if expected_token is not None:
        assert expected_token in calls, f"Expected token {expected_token!r} in stub call log, got: {calls!r}"


@pytest.mark.integration
def test_zsh_available() -> None:
    """AC-FUNC-008: zsh is available; fail with actionable error if not."""
    _assert_zsh_available()


@pytest.mark.integration
def test_completion_script_starts_with_compdef() -> None:
    """AC-FUNC-004: live completion script first non-blank line is '#compdef mpm'."""
    _assert_zsh_available()
    script = _mpm_completion_script()
    non_blank_lines = [line for line in script.splitlines() if line.strip()]
    assert non_blank_lines, "Generated zsh completion script is empty"
    first_line = non_blank_lines[0]
    assert first_line == "#compdef mpm", f"Expected first non-blank line to be '#compdef mpm', got: {first_line!r}"


@pytest.mark.integration
def test_completion_script_syntax_valid() -> None:
    """AC-FUNC-007: live completion script passes ``zsh -n`` before any test case."""
    _assert_zsh_available()
    script = _mpm_completion_script()
    _zsh_syntax_check(script)


_ENUM_FLAG_ROWS: list[tuple[str, str, str, list[str], bool]] = [
    (
        "search_format_enum",
        "_shtab_mpm_search_options",
        "list_format",
        ["names", "json"],
        True,
    ),
    (
        "outdated_format_enum",
        "_shtab_mpm_outdated_options",
        "format",
        ["table", "json"],
        True,
    ),
    (
        "why_format_enum",
        "_shtab_mpm_why_options",
        "format",
        ["text", "json"],
        True,
    ),
    (
        "catalog_audit_format_enum",
        "_shtab_mpm_catalog_audit_options",
        "format",
        ["text", "json"],
        True,
    ),
    (
        "validate_metadata_format_enum",
        "_shtab_mpm_validate_metadata_options",
        "format",
        ["text", "json"],
        True,
    ),
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "test_id,option_array_name,label,expected,exact_match",
    [pytest.param(*row, id=row[0]) for row in _ENUM_FLAG_ROWS],
)
def test_static_enum_flag_row(
    tmp_path: Path,
    test_id: str,
    option_array_name: str,
    label: str,
    expected: list[str],
    exact_match: bool,
) -> None:
    """AC-FUNC-002: static-enum flag rows have the expected choices in option spec arrays.

    For each row: extract the enum choices from the named option spec array
    by label and assert they match or contain the expected candidates.
    """
    _assert_zsh_available()
    choices = _zsh_option_spec_runner(
        tmp_path=tmp_path,
        option_array_name=option_array_name,
        label=label,
    )
    assert choices, (
        f"[{test_id}] No choices extracted from {option_array_name!r} "
        f"for label {label!r}. Option spec array may be empty or label may not match."
    )
    if exact_match:
        assert sorted(choices) == sorted(expected), (
            f"[{test_id}] Expected exact choices {sorted(expected)!r}, got {sorted(choices)!r}"
        )
    else:
        missing = [c for c in expected if c not in choices]
        assert not missing, (
            f"[{test_id}] Expected choices to contain {expected!r}, but missing {missing!r}. Got: {sorted(choices)!r}"
        )


@pytest.mark.integration
def test_static_completion_shell_enum(tmp_path: Path) -> None:
    """AC-FUNC-002: 'mpm completion <TAB>' offers (bash, zsh, powershell) as positional choices."""
    _assert_zsh_available()
    choices = _zsh_positional_spec_runner(
        tmp_path=tmp_path,
        option_array_name="_shtab_mpm_completion_options",
        pattern="bash zsh powershell",
    )
    assert sorted(choices) == ["bash", "powershell", "zsh"], (
        f"Expected completion shell choices ['bash', 'powershell', 'zsh'], got {sorted(choices)!r}"
    )


_FLAG_PRESENCE_ROWS: list[tuple[str, str, list[str]]] = [
    (
        "search_flags",
        "_shtab_mpm_search_options",
        ["--help", "--format", "--detail", "--tree", "--all", "--no-limit"],
    ),
    (
        "search_match_fields_flag",
        "_shtab_mpm_search_options",
        ["--match-fields"],
    ),
    (
        "search_since_version_flag",
        "_shtab_mpm_search_options",
        ["--since-version"],
    ),
    (
        "search_regex_flag",
        "_shtab_mpm_search_options",
        ["--regex"],
    ),
    (
        "outdated_flags",
        "_shtab_mpm_outdated_options",
        ["--help", "--format", "--fail-on-upgrade", "--mpm-file", "--lock-file"],
    ),
    (
        "why_flags",
        "_shtab_mpm_why_options",
        ["--help", "--format", "--mpm-file", "--lock-file"],
    ),
    (
        "catalog_audit_flags",
        "_shtab_mpm_catalog_audit_options",
        ["--check", "--format", "--strict"],
    ),
    (
        "add_flags",
        "_shtab_mpm_add_options",
        ["--help", "--force", "--dry-run", "--mpm-file"],
    ),
    (
        "add_catalog_source_flag",
        "_shtab_mpm_add_options",
        ["--catalog-source"],
    ),
    (
        "remove_flags",
        "_shtab_mpm_remove_options",
        ["--help", "--force", "--dry-run", "--mpm-file"],
    ),
    (
        "install_flags",
        "_shtab_mpm_install_options",
        ["--help", "--refresh-lock", "--strict-lock", "--strict-drift", "--lock-file"],
    ),
    (
        "install_refresh_lock_source_flag",
        "_shtab_mpm_install_options",
        ["--refresh-lock-source"],
    ),
    (
        "doctor_flags",
        "_shtab_mpm_doctor_options",
        ["--help", "--refresh-completion-cache", "--strict-drift", "--prune-cache"],
    ),
    (
        "doctor_filesystem_flags",
        "_shtab_mpm_doctor_options",
        ["--mpm-file", "--lock-file"],
    ),
    (
        "validate_xml_repo_root_flag",
        "_shtab_mpm_validate_xml_options",
        ["--repo-root"],
    ),
    (
        "validate_marketplace_repo_root_flag",
        "_shtab_mpm_validate_marketplace_options",
        ["--repo-root"],
    ),
    (
        "validate_metadata_repo_root_flag",
        "_shtab_mpm_validate_metadata_options",
        ["--repo-root"],
    ),
    (
        "clean_flags",
        "_shtab_mpm_clean_options",
        ["--help"],
    ),
    (
        "repo_repo_dir_flag",
        "_shtab_mpm_repo_options",
        ["--repo-dir"],
    ),
    (
        "global_flags",
        "_shtab_mpm_options",
        ["--help", "--version", "--quiet", "--verbose", "--no-color"],
    ),
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "test_id,option_array_name,expected_flags",
    [pytest.param(*row, id=row[0]) for row in _FLAG_PRESENCE_ROWS],
)
def test_static_flag_presence_row(
    tmp_path: Path,
    test_id: str,
    option_array_name: str,
    expected_flags: list[str],
) -> None:
    """AC-FUNC-002: static flag rows have the expected flags in option spec arrays.

    For each row: extract all flag names from the named option spec array
    and assert each expected flag is present.
    """
    _assert_zsh_available()
    completion_file = _write_completion_file(tmp_path)

    flags_script = textwrap.dedent(f"""\
        _arguments() {{ return 0; }}
        compdef() {{ return 0; }}
        _describe() {{ return 0; }}
        source {completion_file}
        local varname="{option_array_name}"
        local -a arr
        arr=("${{(@P)varname}}")
        for opt in "${{arr[@]}}"; do
            # Match --flag or (-h,--help) patterns
            if [[ "$opt" == *"--"* ]]; then
                # Extract all --flag occurrences
                local tmp="$opt"
                while [[ "$tmp" == *"--"* ]]; do
                    tmp="${{tmp#*--}}"
                    local flag="${{tmp%%[^a-zA-Z0-9-]*}}"
                    [[ -n "$flag" ]] && printf 'FLAG:--%s\\n' "$flag"
                    tmp="${{tmp#${{flag}}}}"
                done
            fi
        done
        """)

    result = subprocess.run(
        ["zsh", "-fc", flags_script],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"[{test_id}] Flag extraction script failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    found_flags = {line[len("FLAG:") :] for line in result.stdout.splitlines() if line.startswith("FLAG:")}
    missing = [f for f in expected_flags if f not in found_flags]
    assert not missing, (
        f"[{test_id}] Expected flags {expected_flags!r} to be present in "
        f"{option_array_name!r}, but missing {missing!r}. Found: {sorted(found_flags)!r}"
    )


@pytest.mark.integration
def test_bootstrap_option_array_has_no_flags(tmp_path: Path) -> None:
    """`_shtab_mpm_bootstrap_options` carries no `--flag` entries.

    bootstrap was removed in a major release and is now a flagless deprecation
    shim (the subparser declares only a REMAINDER catch-all), so its zsh option
    spec must not advertise `--output-dir`, `--catalog-source`, or `--help`.
    """
    _assert_zsh_available()
    completion_file = _write_completion_file(tmp_path)

    flags_script = textwrap.dedent(f"""\
        _arguments() {{ return 0; }}
        compdef() {{ return 0; }}
        _describe() {{ return 0; }}
        source {completion_file}
        local varname="_shtab_mpm_bootstrap_options"
        local -a arr
        arr=("${{(@P)varname}}")
        for opt in "${{arr[@]}}"; do
            if [[ "$opt" == *"--"* ]]; then
                local tmp="$opt"
                while [[ "$tmp" == *"--"* ]]; do
                    tmp="${{tmp#*--}}"
                    local flag="${{tmp%%[^a-zA-Z0-9-]*}}"
                    [[ -n "$flag" ]] && printf 'FLAG:--%s\\n' "$flag"
                    tmp="${{tmp#${{flag}}}}"
                done
            fi
        done
        """)

    result = subprocess.run(["zsh", "-fc", flags_script], capture_output=True, text=True)
    assert result.returncode == 0, (
        f"Flag extraction script failed (exit {result.returncode}).\n"
        f"stdout: {result.stdout!r}\nstderr: {result.stderr!r}"
    )
    found_flags = sorted({line[len("FLAG:") :] for line in result.stdout.splitlines() if line.startswith("FLAG:")})
    assert found_flags == [], (
        f"bootstrap option spec must advertise no flags (it is a flagless shim), got: {found_flags!r}"
    )


@pytest.mark.integration
def test_static_top_level_subcommands(tmp_path: Path) -> None:
    """AC-FUNC-002: top-level subcommands include the expected set."""
    _assert_zsh_available()
    subcommands = _zsh_subcommand_runner(
        tmp_path=tmp_path,
        commands_fn="_shtab_mpm_commands",
    )

    expected = [
        "add",
        "catalog",
        "clean",
        "completion",
        "doctor",
        "install",
        "marketplace",
        "search",
        "outdated",
        "remove",
        "validate",
        "repo",
        "why",
    ]
    missing = [cmd for cmd in expected if cmd not in subcommands]
    assert not missing, (
        f"Expected top-level subcommands to include {expected!r}, but missing {missing!r}. Got: {sorted(subcommands)!r}"
    )

    assert "bootstrap" not in subcommands, (
        f"removed 'bootstrap' must not be a completion subcommand: {sorted(subcommands)!r}"
    )


@pytest.mark.integration
def test_static_catalog_subcommands(tmp_path: Path) -> None:
    """AC-FUNC-002: 'mpm catalog <TAB>' offers exactly ['audit']."""
    _assert_zsh_available()
    subcommands = _zsh_subcommand_runner(
        tmp_path=tmp_path,
        commands_fn="_shtab_mpm_catalog_commands",
    )
    assert "audit" in subcommands, f"Expected 'audit' in catalog subcommands, got {sorted(subcommands)!r}"


@pytest.mark.integration
def test_static_validate_subcommands(tmp_path: Path) -> None:
    """AC-FUNC-002: 'mpm validate <TAB>' offers ['xml', 'marketplace', 'metadata', 'lockfile']."""
    _assert_zsh_available()
    subcommands = _zsh_subcommand_runner(
        tmp_path=tmp_path,
        commands_fn="_shtab_mpm_validate_commands",
    )
    expected = ["xml", "marketplace", "metadata", "lockfile"]
    missing = [cmd for cmd in expected if cmd not in subcommands]
    assert not missing, (
        f"Expected validate subcommands to include {expected!r}, but missing {missing!r}. Got: {sorted(subcommands)!r}"
    )
    assert sorted(subcommands) == sorted(expected), (
        f"Expected exact validate subcommands {sorted(expected)!r}, got {sorted(subcommands)!r}"
    )


@pytest.mark.integration
def test_dynamic_row_add_catalog_entries(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm add <TAB>' -- preamble helper routes to catalog entries.

    Sources the live completion script, invokes _mpm_complete_catalog_entries
    via the stub mpm, and asserts (a) stub called with
    __complete_catalog_entries and (b) compadd receives fixture output.
    """
    _assert_zsh_available()
    fixture_entries = "my-tool\nanother-entry\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["my-tool", "another-entry"]), (
        f"Expected compadd=['my-tool','another-entry'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries")


@pytest.mark.integration
def test_dynamic_row_bootstrap_catalog_entries(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm bootstrap <TAB>' -- preamble routes to catalog entries.

    Section 11.2: bootstrap retains catalog-entry completion for the
    deprecation window via the same _mpm_complete_catalog_entries helper.
    """
    _assert_zsh_available()
    fixture_entries = "legacy-pkg\nold-tool\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["legacy-pkg", "old-tool"]), (
        f"Expected compadd=['legacy-pkg','old-tool'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries")


@pytest.mark.integration
def test_dynamic_row_remove_source_names(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm remove <TAB>' -- preamble routes to source_names_in_mpm."""
    _assert_zsh_available()
    fixture_entries = "source-alpha\nsource-beta\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_source_names_in_mpm": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_source_names_in_mpm ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["source-alpha", "source-beta"]), (
        f"Expected compadd=['source-alpha','source-beta'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_source_names_in_mpm")


@pytest.mark.integration
def test_dynamic_row_install_refresh_lock_source(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm install --refresh-lock-source <TAB>' routes to source_names."""
    _assert_zsh_available()
    fixture_entries = "src-one\nsrc-two\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_source_names_in_mpm": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_source_names_in_mpm ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["src-one", "src-two"]), (
        f"Expected compadd=['src-one','src-two'], got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_source_names_in_mpm")


@pytest.mark.integration
def test_dynamic_row_why_lockfile_names(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm why <TAB>' -- preamble routes to names_in_lockfile."""
    _assert_zsh_available()
    fixture_entries = "locked-entry\nhttps://example.com/repo.git\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_names_in_lockfile": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_names_in_lockfile ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["locked-entry", "https://example.com/repo.git"]), (
        f"Expected lockfile names in compadd, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_names_in_lockfile")


@pytest.mark.integration
def test_dynamic_row_global_catalog_source(tmp_path: Path) -> None:
    """AC-FUNC-003: '--catalog-source <TAB>' -- preamble routes to cached_catalogs."""
    _assert_zsh_available()
    fixture_entries = "https://catalog.example.com/repo.git@main\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_cached_catalogs": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_cached_catalogs ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert candidates == ["https://catalog.example.com/repo.git@main"], (
        f"Expected cached catalog URL in compadd, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_cached_catalogs")


@pytest.mark.integration
def test_dynamic_row_list_since_version(tmp_path: Path) -> None:
    """AC-FUNC-003: 'mpm search --since-version <TAB>' routes to catalog_versions."""
    _assert_zsh_available()
    fixture_entries = "1.0.0\n2.0.0\n3.0.0\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_versions": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_versions ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == ["1.0.0", "2.0.0", "3.0.0"], f"Expected version list in compadd, got {candidates!r}"
    _assert_stub_called_with(call_log_path, "__complete_catalog_versions")


@pytest.mark.integration
def test_dynamic_row_add_no_at_routes_catalog(tmp_path: Path) -> None:
    """AC-FUNC-005 (no-@ path): 'mpm add my-t<TAB>' routes to catalog entries.

    _mpm_complete_add_arg without @ in the token delegates to
    _mpm_complete_catalog_entries.  The stub must be invoked with
    __complete_catalog_entries and the token 'my-t'.
    """
    _assert_zsh_available()
    fixture_entries = "my-tool\nmy-toolbox\n"
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": fixture_entries})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'my-t'",
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert sorted(candidates) == sorted(["my-tool", "my-toolbox"]), (
        f"Expected catalog entries for no-@ token, got {candidates!r}"
    )
    _assert_stub_called_with(call_log_path, "__complete_catalog_entries", "my-t")


@pytest.mark.integration
def test_dynamic_row_add_with_at_routes_project_versions(tmp_path: Path) -> None:
    """AC-FUNC-005 (with-@ path): 'mpm add foo@<TAB>' resolves repo URL then lists versions.

    _mpm_complete_add_arg detects the '@' separator, shells out to
    mpm __resolve_entry_to_repo_url foo to get the repo URL, then calls
    _mpm_complete_project_versions with that URL and the empty spec.
    compadd must receive the project versions returned by the stub.
    """
    _assert_zsh_available()

    repo_url = "https://example.com/foo.git"
    versions_output = "1.0.0\n2.0.0\n"

    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"

    resolve_out = tmp_path / "out_resolve.txt"
    resolve_out.write_text(repo_url + "\n", encoding="utf-8")
    versions_out = tmp_path / "out_versions.txt"
    versions_out.write_text(versions_output, encoding="utf-8")

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        # Stub mpm: supports __resolve_entry_to_repo_url and
        # __complete_project_versions.
        printf '%s\\n' "$*" >> {call_log}
        subcommand="${{1:-}}"
        case "$subcommand" in
            "__resolve_entry_to_repo_url") cat {resolve_out} ;;
            "__complete_project_versions") cat {versions_out} ;;
            "__complete_catalog_entries") ;;
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'foo@'",
        stub_bin_dir=str(stub_dir),
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )

    assert "1.0.0" in candidates, f"Expected '1.0.0' in compadd for 'foo@' completion, got {candidates!r}"
    assert "2.0.0" in candidates, f"Expected '2.0.0' in compadd for 'foo@' completion, got {candidates!r}"

    call_log_text = Path(call_log).read_text(encoding="utf-8") if Path(call_log).exists() else ""
    assert "__resolve_entry_to_repo_url" in call_log_text, (
        f"Expected __resolve_entry_to_repo_url call for 'foo@', got: {call_log_text!r}"
    )
    assert "__complete_project_versions" in call_log_text, (
        f"Expected __complete_project_versions call for 'foo@', got: {call_log_text!r}"
    )


_DYNAMIC_DISABLED_CASES: list[tuple[str, str, str]] = [
    (
        "catalog_entries_disabled",
        '_mpm_complete_catalog_entries ""',
        "__complete_catalog_entries",
    ),
    (
        "source_names_disabled",
        '_mpm_complete_source_names_in_mpm ""',
        "__complete_source_names_in_mpm",
    ),
    (
        "lockfile_names_disabled",
        '_mpm_complete_names_in_lockfile ""',
        "__complete_names_in_lockfile",
    ),
    (
        "catalog_versions_disabled",
        '_mpm_complete_catalog_versions ""',
        "__complete_catalog_versions",
    ),
    (
        "cached_catalogs_disabled",
        '_mpm_complete_cached_catalogs ""',
        "__complete_cached_catalogs",
    ),
    (
        "add_arg_disabled",
        "_mpm_complete_add_arg 'my-entry'",
        "__complete_catalog_entries",
    ),
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "test_id,helper_call,stub_subcommand",
    [pytest.param(*row, id=row[0]) for row in _DYNAMIC_DISABLED_CASES],
)
def test_mpm_completion_enabled_0_returns_empty(
    tmp_path: Path,
    test_id: str,
    helper_call: str,
    stub_subcommand: str,
) -> None:
    """AC-FUNC-006: MPM_COMPLETION_ENABLED=0 causes dynamic helpers to return empty compadd.

    The stub must NOT be invoked when MPM_COMPLETION_ENABLED=0.
    """
    _assert_zsh_available()
    stub_bin_dir, call_log_path = _write_stub_mpm(tmp_path, {stub_subcommand: "fixture-entry\n"})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call=helper_call,
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "0"},
    )
    assert candidates == [], f"[{test_id}] Expected empty compadd when MPM_COMPLETION_ENABLED=0, got {candidates!r}"
    call_log = Path(call_log_path)
    if call_log.exists():
        calls = call_log.read_text(encoding="utf-8").strip()
        assert calls == "", (
            f"[{test_id}] Stub must not be invoked when MPM_COMPLETION_ENABLED=0, but got calls: {calls!r}"
        )


@pytest.mark.integration
def test_ac_cycle_001_search_format(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm search --format <TAB> => (names, json) per option spec."""
    _assert_zsh_available()
    choices = _zsh_option_spec_runner(
        tmp_path=tmp_path,
        option_array_name="_shtab_mpm_search_options",
        label="list_format",
    )
    assert sorted(choices) == ["json", "names"], f"AC-CYCLE-001: expected (names json), got {choices!r}"


@pytest.mark.integration
def test_ac_cycle_001_completion_shell(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm completion <TAB> => (bash, zsh, powershell) per option spec."""
    _assert_zsh_available()
    choices = _zsh_positional_spec_runner(
        tmp_path=tmp_path,
        option_array_name="_shtab_mpm_completion_options",
        pattern="bash zsh powershell",
    )
    assert sorted(choices) == ["bash", "powershell", "zsh"], (
        f"AC-CYCLE-001: expected (bash powershell zsh), got {choices!r}"
    )


@pytest.mark.integration
def test_ac_cycle_001_outdated_format(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm outdated --format <TAB> => (table, json) per option spec."""
    _assert_zsh_available()
    choices = _zsh_option_spec_runner(
        tmp_path=tmp_path,
        option_array_name="_shtab_mpm_outdated_options",
        label="format",
    )
    assert sorted(choices) == ["json", "table"], f"AC-CYCLE-001: expected (table json), got {choices!r}"


@pytest.mark.integration
def test_ac_cycle_001_validate_subcommands(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm validate <TAB> => (xml, marketplace, metadata, lockfile)."""
    _assert_zsh_available()
    subcommands = _zsh_subcommand_runner(
        tmp_path=tmp_path,
        commands_fn="_shtab_mpm_validate_commands",
    )
    assert sorted(subcommands) == ["lockfile", "marketplace", "metadata", "xml"], (
        f"AC-CYCLE-001: expected (xml marketplace metadata lockfile), got {sorted(subcommands)!r}"
    )


@pytest.mark.integration
def test_ac_cycle_001_dynamic_add_with_stub(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm add <TAB> with stub returns fixture entries.

    Steps:
    1. Write stub mpm returning 'my-tool' for __complete_catalog_entries.
    2. Source the live completion script (passes zsh -n check).
    3. Invoke _mpm_complete_catalog_entries (the preamble helper for 'add').
    4. Assert compadd receives 'my-tool' and 'other-pkg'.
    """
    _assert_zsh_available()
    stub_bin_dir, _call_log = _write_stub_mpm(tmp_path, {"__complete_catalog_entries": "my-tool\nother-pkg\n"})
    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call='_mpm_complete_catalog_entries ""',
        stub_bin_dir=stub_bin_dir,
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert "my-tool" in candidates, f"AC-CYCLE-001: expected 'my-tool' in compadd, got {candidates!r}"
    assert "other-pkg" in candidates, f"AC-CYCLE-001: expected 'other-pkg' in compadd, got {candidates!r}"


@pytest.mark.integration
def test_ac_cycle_001_add_at_spec(tmp_path: Path) -> None:
    """AC-CYCLE-001: mpm add foo@ routes to project versions.

    Sources the live completion script; _mpm_complete_add_arg 'foo@'
    resolves the repo URL via the stub and returns version candidates.
    """
    _assert_zsh_available()

    repo_url = "https://example.com/foo.git"
    stub_dir = tmp_path / "stub_bin"
    stub_dir.mkdir(exist_ok=True)
    call_log = tmp_path / "mpm_calls.log"
    resolve_out = tmp_path / "resolve.txt"
    resolve_out.write_text(repo_url + "\n", encoding="utf-8")
    versions_out = tmp_path / "versions.txt"
    versions_out.write_text("1.0.0\n2.0.0\n", encoding="utf-8")

    stub_content = textwrap.dedent(f"""\
        #!/bin/bash
        printf '%s\\n' "$*" >> {call_log}
        case "${{1:-}}" in
            "__resolve_entry_to_repo_url") cat {resolve_out} ;;
            "__complete_project_versions") cat {versions_out} ;;
            *) ;;
        esac
        """)
    stub_path = stub_dir / "mpm"
    stub_path.write_text(stub_content, encoding="utf-8")
    stub_path.chmod(stub_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    candidates = _zsh_completion_runner(
        tmp_path=tmp_path,
        helper_call="_mpm_complete_add_arg 'foo@'",
        stub_bin_dir=str(stub_dir),
        extra_env={"MPM_COMPLETION_ENABLED": "1"},
    )
    assert "1.0.0" in candidates, f"AC-CYCLE-001: expected '1.0.0' in compadd, got {candidates!r}"
    assert "2.0.0" in candidates, f"AC-CYCLE-001: expected '2.0.0' in compadd, got {candidates!r}"
